/**
 * C5 ownership verification — exclusive store ownership at the supervision
 * layer (contract §3/§8), FAIL-CLOSED protocol (no automatic stale recovery).
 *
 * C5 DESIGN (closes C4-exit audit finding L1/Medium): the audit demonstrated
 * a deterministic three-process interleaving in which the stale-recovery
 * rename-aside/restore path let instance A and a fresh instance C run
 * CONCURRENT operations on one physical store. The protocol is now trivially
 * provable: the lock is created ONLY via atomic `O_EXCL` ('wx'), replaced
 * ONLY by its owner's heartbeat (atomic tmp→rename of its own lock), and
 * deleted ONLY by its owner's orderly release or an explicit OPERATOR action
 * (contract §8.1). A contender REFUSES whenever a lock exists — live or
 * stale — and never moves, overwrites, or deletes it. Acceptance: no
 * concurrent operations on one physical store, including during recovery.
 *
 * Run (from repo root):
 *   ../260831-VCT-02/node_modules/.bin/tsx pack/verify/ownership-verify.ts
 *
 * Fresh disposable store (proof/.cognee-ownership, own .env):
 *  O1  first pack instance claims exclusive ownership (lock file, held);
 *  O2  a SECOND pack instance on the SAME store fails closed
 *      (COGNEE_STORE_OWNED) at construction — before any worker spawn;
 *  O3  the owning instance runs a real worker op under ownership; orderly
 *      shutdown RELEASES ownership; a new instance acquires it (restart);
 *  O4  CRASH/RESTART with OPERATOR recovery: a lock whose owner pid is
 *      verifiably DEAD is NOT auto-recovered — a new instance REFUSES with
 *      the owner record + operator guidance in the message, the lock bytes
 *      are untouched; after the operator step (delete the lock, which the
 *      harness performs only after verifying the pid is dead — the §8.1
 *      procedure) a new instance acquires cleanly;
 *  O2b a crafted lock belonging to a LIVE owner (live pid) fails closed and
 *      is NEVER deleted — AND the instance whose lock was replaced by the
 *      crafted one fails closed on its next operation (no spawn, no
 *      dispatch), and its idle worker (if any) is killed (orphan facet);
 *  O6  an active instance whose lock file is REMOVED fails closed on the
 *      next op and stays failed (sticky);
 *  O7  DETERMINISTIC two-contender race: against a stale lock BOTH
 *      contenders refuse (lock bytes untouched by both); after operator
 *      recovery two fresh contenders race for the FREE store — exactly one
 *      acquires (O_EXCL), the other fails closed, winner's lock intact;
 *  O8  a contender NEVER removes a fresh LIVE lock: it fails closed, the
 *      live owner's lock bytes are unchanged, and the owner keeps holding;
 *  O9  foreign-host budget: fresh-heartbeat foreign owner is refused; a
 *      stale-heartbeat foreign owner is ALSO refused (no auto-recovery —
 *      cross-host coordination is the operator's §8.1 procedure); the
 *      heartbeat is still refreshed DURING long in-flight operations;
 *  O10 REGRESSION of the auditor's three-process interleaving: while A
 *      operates, contender roles B and C both refuse pre-spawn (nothing
 *      dispatched, A's lock untouched); source assertion: the supervision
 *      contains NO recovery-rename path (exactly one renameSync — the
 *      owner's heartbeat replace — and no `.recovering-` markers);
 *  O5  resource recording (spawns, ops, wall clock).
 */

import { writeFileSync, mkdirSync, rmSync, readFileSync, existsSync, unlinkSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { hostname } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createCogneePack, WorkerError } from '../src/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const VICT = path.resolve(repo, '..', '260831-VCT-02');
const PY = path.join(repo, 'proof', '.venv', 'Scripts', 'python.exe');
const STUB = path.join(here, 'stub_worker.py');
const NAMESPACES = ['qa'];
const STORE = path.join(repo, 'proof', '.cognee-ownership');
const RACE1 = path.join(repo, 'proof', '.cognee-ownership-race1');
const RACE2 = path.join(repo, 'proof', '.cognee-ownership-race2');
const HBSTORE = path.join(repo, 'proof', '.cognee-ownership-hb');
const LOCK = path.join(STORE, 'cognee-store-owner.lock');

function sleep(ms: number): Promise<void> { return new Promise((r) => setTimeout(r, ms)); }

async function freshDir(dir: string): Promise<void> {
  for (let attempt = 0; ; attempt++) {
    try { rmSync(dir, { recursive: true, force: true }); break; }
    catch {
      if (attempt >= 4) throw new Error(`cannot clear ${dir}`);
      await sleep(2_000); // transient EBUSY (Windows)
    }
  }
  mkdirSync(dir, { recursive: true });
}

await freshDir(STORE);
writeFileSync(path.join(STORE, '.env'), [
  '# Fresh disposable ownership-verification store (generated by ownership-verify.ts)',
  'ENV=dev', 'RUNTIME__LOG_LEVEL=INFO',
  ...Object.entries({
    SYSTEM_ROOT_DIRECTORY: 'system', DATA_ROOT_DIRECTORY: 'data',
    CACHE_ROOT_DIRECTORY: 'cache', LOGS_ROOT_DIRECTORY: 'logs',
    COGNEE_REPOS_DIR: 'repos',
  }).map(([k, v]) => `${k}=${path.join(STORE, v).replace(/\\/g, '/')}`),
  'VECTOR_DB_PROVIDER=lancedb', 'GRAPH_DATABASE_PROVIDER=ladybug',
  'DB_PROVIDER=sqlite', 'EMBEDDING_PROVIDER=fastembed',
  'EMBEDDING_MODEL=BAAI/bge-small-en-v1.5', 'EMBEDDING_DIMENSIONS=384',
  'GRAPH_EXTRACTOR=gliner_demo', 'AUTO_FEEDBACK=false', '',
].join('\n'));

const t0 = Date.now();
const results: { id: string; name: string; outcome: string; detail?: unknown; ms?: number }[] = [];
function check(id: string, name: string, cond: boolean, detail?: unknown, ms?: number): boolean {
  results.push({ id, name, outcome: cond ? 'PASS' : 'FAIL', detail, ms });
  console.error(`[own] ${id} ${cond ? 'PASS' : 'FAIL'} ${name} ${ms !== undefined ? `(${ms}ms)` : ''}`);
  return cond;
}

// ---- C5 (audit M1): controlled failing assertion ----------------------------
// C5_FORCED_FAIL=1 records one deliberately failing assertion and exits 1
// WITHOUT running the suite — proving the exit-status coupling.
if (process.env.C5_FORCED_FAIL === '1') {
  console.error('[own] forced-fail: controlled failing assertion (C5_FORCED_FAIL=1)');
  results.push({ id: 'forced-fail', name: 'controlled failing assertion', outcome: 'FAIL', detail: { forced: true } });
  writeFileSync(path.join(repo, 'worker', 'c4-ownership-results.json'), JSON.stringify({
    verification: 'c5-store-ownership-fail-closed', forcedFail: true,
    started: new Date().toISOString(), duration_s: 0, results,
  }, null, 2));
  process.exit(1);
}

function makePack(store = STORE, extra: Record<string, unknown> = {}):
  ReturnType<typeof createCogneePack> {
  return createCogneePack({
    pythonPath: PY, cwd: store, storeRoot: store, namespaces: NAMESPACES,
    readyBudgetMs: 180_000,
    diag: (line) => console.error(`[own-sup] ${line.slice(0, 140)}`),
    ...extra,
  });
}

function readHeartbeat(lockPath: string): string | null {
  try {
    return (JSON.parse(readFileSync(lockPath, 'utf8')) as { heartbeatAt?: string }).heartbeatAt ?? null;
  } catch { return null; }
}

/** Spawn a contender child; resolves its NDJSON done-event. */
interface ContenderEvent { event: string; acquired?: boolean; code?: string; message?: string; instanceId?: string }
function contender(store: string, hold = false): {
  done: Promise<ContenderEvent>;
  child: ReturnType<typeof spawn>;
} {
  const child = spawn(process.execPath, [
    path.join(VICT, 'node_modules', 'tsx', 'dist', 'cli.mjs'),
    path.join(here, 'ownership-contender.ts'), store, ...(hold ? ['hold'] : []),
  ], { cwd: repo, stdio: ['ignore', 'pipe', 'inherit'] });
  const done = new Promise<ContenderEvent>((resolve) => {
    let buf = '';
    child.stdout!.on('data', (d: Buffer) => {
      buf += String(d);
      let idx: number;
      while ((idx = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, idx).trim();
        buf = buf.slice(idx + 1);
        if (!line) continue;
        try {
          const ev = JSON.parse(line) as ContenderEvent;
          if (ev.event === 'done') { resolve(ev); return; }
        } catch { /* partial */ }
      }
    });
    child.on('exit', () => resolve({ event: 'done', acquired: false, code: 'CHILD_EXITED' }));
  });
  return { done, child };
}

/** A reliably-dead pid (spawn + reap a trivial node process). */
async function deadPid(): Promise<number> {
  const p = spawn(process.execPath, ['-e', 'process.exit(0)'], { stdio: 'ignore' });
  const pid = p.pid!;
  await new Promise((r) => { p.on('exit', () => r(null)); setTimeout(() => r(null), 5_000); });
  return pid;
}

function craftLock(lockPath: string, o: { pid: number; instanceId: string; heartbeatAgeMs: number; host?: string }): string {
  const raw = JSON.stringify({
    schema: 'vict.cognee.store-ownership@1',
    instanceId: o.instanceId,
    pid: o.pid, host: o.host ?? hostname(),
    startedAt: new Date(Date.now() - Math.max(o.heartbeatAgeMs, 60_000)).toISOString(),
    heartbeatAt: new Date(Date.now() - o.heartbeatAgeMs).toISOString(),
  });
  writeFileSync(lockPath, raw);
  return raw;
}

// ---- O1: first instance claims exclusive ownership --------------------------
let packA: ReturnType<typeof createCogneePack> | null = null;
{
  const t = Date.now();
  try {
    packA = makePack();
    const rec = JSON.parse(readFileSync(LOCK, 'utf8')) as { pid?: number; instanceId?: string };
    check('O1', 'first instance claims exclusive store ownership (lock held, pid recorded)',
      packA.supervision.storeOwnershipHeld && rec.pid === process.pid &&
        typeof rec.instanceId === 'string',
      { lockPid: rec.pid, held: packA.supervision.storeOwnershipHeld }, Date.now() - t);
  } catch (e) {
    check('O1', 'first instance claims exclusive store ownership', false,
      { error: String(e) }, Date.now() - t);
    throw e;
  }
}

// ---- O2: second instance fails closed (pre-spawn) ----------------------------
{
  const t = Date.now();
  let refused: unknown = null;
  try { makePack(); } catch (e) { refused = e; }
  const we = refused instanceof WorkerError ? refused : null;
  check('O2', 'second pack instance on the SAME store fails closed (COGNEE_STORE_OWNED, pre-spawn, operator guidance in message)',
    we?.code === 'COGNEE_STORE_OWNED' && packA!.supervision.stats.spawns === 0 &&
      typeof we?.message === 'string' && we.message.includes('§8.1'),
    { code: we?.code ?? String(refused), spawns: packA!.supervision.stats.spawns,
      guidance: we?.message.includes('§8.1') === true }, Date.now() - t);
}

// ---- O3: real op under ownership + orderly shutdown releases + restart -------
{
  const t = Date.now();
  // packA holds ownership; the lock is its own — a real op must run.
  const searchBinding = packA!.bindings.capabilities.find((b) => b.id === 'cognee.searchChunks')!;
  try {
    await searchBinding.invoke({ datasets: ['qa.any'], query: 'warmup' }, { mode: 'normal' });
  } catch {
    // typed dataset-unknown/worker error is acceptable here: the point is
    // that the worker RAN under exclusive ownership (spawn + lock intact).
  }
  const ran = packA!.supervision.stats.spawns >= 1 && packA!.supervision.storeOwnershipHeld;
  check('O3a', 'worker op runs under held exclusive ownership (spawn + lock intact)',
    ran, { spawns: packA!.supervision.stats.spawns,
      held: packA!.supervision.storeOwnershipHeld }, Date.now() - t);
  const t2 = Date.now();
  await packA!.supervision.shutdown();
  check('O3b', 'orderly shutdown RELEASES ownership (lock gone)',
    !packA!.supervision.storeOwnershipHeld && !existsSync(LOCK),
    { held: packA!.supervision.storeOwnershipHeld }, Date.now() - t2);
  const t3 = Date.now();
  const packC = makePack();
  const reacquired = packC.supervision.storeOwnershipHeld && existsSync(LOCK);
  check('O3c', 'restart: a new instance acquires ownership after orderly release',
    reacquired, {}, Date.now() - t3);
  packC.supervision.releaseStoreOwnership();
}

// ---- O4: crash/restart — a dead owner's lock is NOT auto-recovered; the §8.1
// operator procedure recovers it ------------------------------------------------
{
  const t = Date.now();
  const pid = await deadPid();
  const crafted = craftLock(LOCK, { pid, instanceId: 'dead-owner-00000000', heartbeatAgeMs: 3_600_000 });
  // (i) a new instance REFUSES on the stale (dead-pid) lock — no auto-recovery.
  let refused: unknown = null;
  try { makePack(); } catch (e) { refused = e; }
  const we = refused instanceof WorkerError ? refused : null;
  const untouched = readFileSync(LOCK, 'utf8') === crafted;
  const guidance = typeof we?.message === 'string' &&
    we.message.includes(String(pid)) && we.message.includes('NOT running') &&
    we.message.includes('§8.1');
  // (ii) the OPERATOR step: the harness has verified the pid is dead (deadPid()
  // reaped the process) — exactly the §8.1 precondition — and deletes the lock.
  unlinkSync(LOCK);
  // (iii) after operator recovery a new instance acquires cleanly.
  const packD = makePack();
  check('O4', 'crash/restart: dead-pid lock is refused (never auto-recovered, bytes untouched, owner record + procedure in message); after the §8.1 operator step a new instance acquires',
    we?.code === 'COGNEE_STORE_OWNED' && untouched && guidance &&
      packD.supervision.storeOwnershipHeld,
    { refused: we?.code ?? String(refused), lockUntouched: untouched,
      guidanceInMessage: guidance, recovered: packD.supervision.storeOwnershipHeld },
    Date.now() - t);
  packD.supervision.releaseStoreOwnership();
}

// ---- O2b (revised): replaced lock => the ACTIVE instance fails closed --------
// The crafted live-owner lock REPLACES the active instance's lock. The test
// cannot pass while the active instance has lost ownership: its next op MUST
// fail closed (no spawn, no dispatch), and the contender must never delete
// the live owner's lock.
{
  const t = Date.now();
  const packE = makePack(); // fresh ACTIVE instance, owns the lock
  const sleeper = spawn(process.execPath, ['-e', 'setInterval(()=>{},1e6)'], { stdio: 'ignore' });
  await sleep(300);
  const crafted = craftLock(LOCK, {
    pid: sleeper.pid!, instanceId: 'crafted-live-owner-0000', heartbeatAgeMs: 600_000,
  });
  // (i) a contender fails closed against the crafted LIVE owner...
  let refused: unknown = null;
  try { makePack(); } catch (e) { refused = e; }
  const we = refused instanceof WorkerError ? refused : null;
  const unchanged = readFileSync(LOCK, 'utf8') === crafted;
  // (ii) ...and the ACTIVE instance whose lock was replaced performs NO
  // further operation: pre-spawn refusal, nothing dispatched (opsServed 0).
  let lostErr: unknown = null;
  const servedBefore = packE.supervision.stats.opsServed;
  const spawnsBefore = packE.supervision.stats.spawns;
  try {
    const searchBinding = packE.bindings.capabilities.find((b) => b.id === 'cognee.searchChunks')!;
    await searchBinding.invoke({ datasets: ['qa.any'], query: 'x' }, { mode: 'normal' });
  } catch (e) { lostErr = e; }
  const lost = lostErr instanceof WorkerError ? lostErr : null;
  let sticky: unknown = null;
  try {
    await packE.supervision.request('search_chunks', { datasets: ['qa.any'], query: 'x' },
      { mutating: false });
  } catch (e) { sticky = e; }
  const stickyErr = sticky instanceof WorkerError ? sticky : null;
  check('O2b', 'replaced lock: live owner protected (never deleted) AND the active instance fails closed on its next op (no spawn, no dispatch)',
    we?.code === 'COGNEE_STORE_OWNED' && unchanged &&
      lost?.code === 'COGNEE_STORE_OWNED' &&
      packE.supervision.stats.opsServed === servedBefore &&
      packE.supervision.stats.spawns === spawnsBefore &&
      stickyErr?.code === 'COGNEE_STORE_OWNED',
    { contender: we?.code ?? String(refused), lockUnchanged: unchanged,
      activeInstance: lost?.code ?? String(lostErr), spawns: packE.supervision.stats.spawns,
      opsServed: packE.supervision.stats.opsServed, sticky: stickyErr?.code ?? null },
    Date.now() - t);
  sleeper.kill('SIGKILL');
  unlinkSync(LOCK); // harness cleanup of the CRAFTED lock (owner already verified live-protected)
  await packE.supervision.shutdown();
}

// ---- O6: REMOVED lock => active instance performs no further operation -------
{
  const t = Date.now();
  const packF = makePack(); // fresh active instance, owns the lock
  const servedBefore = packF.supervision.stats.opsServed;
  const spawnsBefore = packF.supervision.stats.spawns;
  unlinkSync(LOCK); // external removal
  let lostErr: unknown = null;
  try {
    const searchBinding = packF.bindings.capabilities.find((b) => b.id === 'cognee.searchChunks')!;
    await searchBinding.invoke({ datasets: ['qa.any'], query: 'x' }, { mode: 'normal' });
  } catch (e) { lostErr = e; }
  const lost = lostErr instanceof WorkerError ? lostErr : null;
  let sticky: unknown = null;
  try {
    await packF.supervision.request('search_chunks', { datasets: ['qa.any'], query: 'x' },
      { mutating: false });
  } catch (e) { sticky = e; }
  const stickyErr = sticky instanceof WorkerError ? sticky : null;
  check('O6', 'removed lock: the active instance performs NO further operation (fail closed, sticky)',
    lost?.code === 'COGNEE_STORE_OWNED' &&
      packF.supervision.stats.opsServed === servedBefore &&
      packF.supervision.stats.spawns === spawnsBefore &&
      stickyErr?.code === 'COGNEE_STORE_OWNED',
    { first: lost?.code ?? String(lostErr), sticky: stickyErr?.code ?? null,
      spawns: packF.supervision.stats.spawns, opsServed: packF.supervision.stats.opsServed },
    Date.now() - t);
  await packF.supervision.shutdown();
}

// ---- O7: two contenders vs a STALE lock (both refuse; lock untouched), then
// an O_EXCL race for the FREED store (exactly one winner) -----------------------
{
  const t = Date.now();
  await freshDir(RACE1);
  const raceLock = path.join(RACE1, 'cognee-store-owner.lock');
  const pid = await deadPid();
  const staleBytes = craftLock(raceLock, { pid, instanceId: 'race-stale-owner-000', heartbeatAgeMs: 3_600_000 });
  const [a, b] = [contender(RACE1, true), contender(RACE1, true)]; // simultaneous contenders
  const [ra, rb] = await Promise.all([a.done, b.done]);
  const untouchedAfterRefusals = readFileSync(raceLock, 'utf8') === staleBytes;
  a.child.kill('SIGKILL'); b.child.kill('SIGKILL');
  check('O7a', 'two contenders vs a stale lock: BOTH refuse (no auto-recovery), lock bytes untouched by both',
    ra.acquired === false && rb.acquired === false &&
      ra.code === 'COGNEE_STORE_OWNED' && rb.code === 'COGNEE_STORE_OWNED' &&
      untouchedAfterRefusals,
    { results: [ra, rb], lockUntouched: untouchedAfterRefusals }, Date.now() - t);
  // Operator recovery (§8.1; the harness verified the pid is dead above).
  unlinkSync(raceLock);
  // Now two FRESH contenders race for the FREE store: exactly one wins O_EXCL.
  const t2 = Date.now();
  const [c, d] = [contender(RACE1, true), contender(RACE1, true)];
  const [rc, rd] = await Promise.all([c.done, d.done]);
  const winner = [rc, rd].find((r) => r.acquired === true);
  const loser = [rc, rd].find((r) => r.acquired === false);
  const finalLock = ((): { instanceId?: string } | null => {
    try { return JSON.parse(readFileSync(raceLock, 'utf8')) as { instanceId?: string }; }
    catch { return null; }
  })();
  check('O7b', 'after operator recovery, two fresh contenders race for the free store: EXACTLY ONE acquires (O_EXCL), the other fails closed, winner lock intact',
    !!winner && !!loser && loser!.code === 'COGNEE_STORE_OWNED' &&
      !!finalLock && finalLock.instanceId === winner!.instanceId,
    { results: [rc, rd], winnerLock: finalLock }, Date.now() - t2);
  c.child.kill('SIGKILL'); d.child.kill('SIGKILL');
}

// ---- O8: a contender NEVER removes a fresh LIVE lock --------------------------
{
  const t = Date.now();
  await freshDir(RACE2);
  const raceLock = path.join(RACE2, 'cognee-store-owner.lock');
  // B acquires and HOLDS the live lock.
  const b = contender(RACE2, true);
  const rb = await b.done;
  const freshBytes = existsSync(raceLock) ? readFileSync(raceLock, 'utf8') : null;
  // A stale-judgment contender (any second instance) refuses WITHOUT touching
  // the lock — there is no recovery path in the protocol.
  const a = contender(RACE2, false);
  const ra = await a.done;
  const bytesAfterA = existsSync(raceLock) ? readFileSync(raceLock, 'utf8') : null;
  const bStillAlive = !b.child.killed && b.child.exitCode === null;
  check('O8', 'contender vs a fresh LIVE lock: refuses, lock bytes unchanged, owner keeps holding',
    rb.acquired === true && ra.acquired === false && ra.code === 'COGNEE_STORE_OWNED' &&
      bytesAfterA === freshBytes && bStillAlive,
    { freshOwner: rb, contender: ra, lockUnchanged: bytesAfterA === freshBytes },
    Date.now() - t);
  b.child.kill('SIGKILL');
  a.child.kill('SIGKILL');
}

// ---- O9: foreign-host heartbeat budget + in-flight (long-op) heartbeat -------
{
  await freshDir(HBSTORE);
  const hbLock = path.join(HBSTORE, 'cognee-store-owner.lock');
  const sleeper = spawn(process.execPath, ['-e', 'setInterval(()=>{},1e6)'], { stdio: 'ignore' });
  await sleep(300);
  // (a) foreign host, FRESH heartbeat => treated as LIVE (refused).
  {
    const t = Date.now();
    const fresh = craftLock(hbLock, {
      pid: sleeper.pid!, instanceId: 'foreign-fresh-000000', heartbeatAgeMs: 1_000,
      host: 'other-host.example',
    });
    let refused: unknown = null;
    try { makePack(HBSTORE); } catch (e) { refused = e; }
    const we = refused instanceof WorkerError ? refused : null;
    const unchanged = readFileSync(hbLock, 'utf8') === fresh;
    check('O9a', 'foreign-host owner with FRESH heartbeat is refused (heartbeat liveness)',
      we?.code === 'COGNEE_STORE_OWNED' && unchanged,
      { code: we?.code ?? String(refused), unchanged }, Date.now() - t);
  }
  // (b) foreign host, STALE heartbeat (beyond the budget) => ALSO refused:
  // no automatic recovery — cross-host liveness cannot be verified from here,
  // so recovery is the operator's §8.1 procedure (coordinate, verify, delete).
  {
    const t = Date.now();
    const stale = craftLock(hbLock, {
      pid: sleeper.pid!, instanceId: 'foreign-stale-000000', heartbeatAgeMs: 20 * 60_000,
      host: 'other-host.example',
    });
    let refused: unknown = null;
    try { makePack(HBSTORE); } catch (e) { refused = e; }
    const we = refused instanceof WorkerError ? refused : null;
    const unchanged = readFileSync(hbLock, 'utf8') === stale;
    const guidance = typeof we?.message === 'string' &&
      we.message.includes('other-host.example') && we.message.includes('§8.1');
    check('O9b', 'foreign-host owner with STALE heartbeat is REFUSED (no auto-recovery; foreign host named; operator procedure in message)',
      we?.code === 'COGNEE_STORE_OWNED' && unchanged && guidance,
      { code: we?.code ?? String(refused), unchanged, guidanceInMessage: guidance },
      Date.now() - t);
    unlinkSync(hbLock); // operator step (foreign owner verified as the test sleeper, controlled by this harness)
  }
  // (c) in-flight heartbeat during a LONG operation: with a 1.5 s staleness
  // budget and a 4 s op, the heartbeat must be refreshed DURING the op (a
  // foreign-host contender must never see it go stale while it runs). The
  // probe POLLS for the heartbeat to advance (deterministic against
  // spawn-speed variance) instead of sleeping a fixed interval.
  {
    const t = Date.now();
    const pack9 = makePack(HBSTORE, {
      workerPath: STUB, ownershipStaleMs: 1_500, readyBudgetMs: 30_000,
      env: { STUB_OP_DELAY_MS: '4000' },
    });
    const hb1 = readHeartbeat(hbLock);
    const opPromise = pack9.supervision.request('add',
      { datasetName: 'qa.hb', content: 'long op' }, { mutating: true, deadlineAt: Date.now() + 30_000 });
    let hb2 = hb1;
    const pollStart = Date.now();
    while (Date.now() - pollStart < 2_600) {
      await sleep(150);
      const hb = readHeartbeat(hbLock);
      if (hb && hb !== hb1) { hb2 = hb; break; }
    }
    let midOpRefused: unknown = null;
    try { makePack(HBSTORE); } catch (e) { midOpRefused = e; }
    const midWe = midOpRefused instanceof WorkerError ? midOpRefused : null;
    const receipt = await opPromise as { servedOps?: number };
    check('O9c', 'long op: heartbeat refreshed DURING the op (budget never erodes) and a second instance is refused mid-op; op completes',
      hb1 !== null && hb2 !== null && hb2 !== hb1 &&
        midWe?.code === 'COGNEE_STORE_OWNED' && receipt?.servedOps === 1,
      { hb1, hb2, advancedMs: hb1 && hb2 ? Date.parse(hb2!) - Date.parse(hb1!) : null,
        midOp: midWe?.code ?? String(midOpRefused), receipt }, Date.now() - t);
    await pack9.supervision.shutdown();
  }
  sleeper.kill('SIGKILL');
}

// ---- O10: REGRESSION — the auditor's three-process interleaving ---------------
// Audit (docs/c4-exit-audit.md L1): A operates; the old recoverer B moved A's
// lock, C acquired the free path and DISPATCHED, and A+C ran concurrent ops
// until C's settlement. Under the C5 protocol B/C cannot exist: any second/
// third instance refuses pre-spawn while ANY lock exists, and no pack code
// path moves a lock out of its path.
{
  const t = Date.now();
  await freshDir(RACE2);
  const iLock = path.join(RACE2, 'cognee-store-owner.lock');
  // A: acquires and runs a 4 s op (stub worker).
  const packI = makePack(RACE2, {
    workerPath: STUB, readyBudgetMs: 30_000, env: { STUB_OP_DELAY_MS: '4000' },
  });
  const opA = packI.supervision.request('add', { datasetName: 'qa.o10', content: 'x' },
    { mutating: true, deadlineAt: Date.now() + 30_000 });
  await sleep(1_000); // A dispatched, op in flight
  // B and C (the audit's recoverer and third instance): both must refuse,
  // pre-spawn, while A's lock exists.
  const b = contender(RACE2, false);
  const c = contender(RACE2, false);
  const [rb, rc] = await Promise.all([b.done, c.done]);
  const servedByA = packI.supervision.stats.opsServed;
  const spawnsByA = packI.supervision.stats.spawns;
  const receipt = await opA as { servedOps?: number };
  const lockIntact = existsSync(iLock) &&
    (JSON.parse(readFileSync(iLock, 'utf8')) as { instanceId?: string }).instanceId !== undefined;
  // Source assertion: the ONLY renameSync is the owner's heartbeat replace —
  // no recovery rename exists; no `.recovering-` trash names exist.
  const supSource = readFileSync(path.join(repo, 'pack', 'src', 'supervision.ts'), 'utf8');
  const renameCount = (supSource.match(/renameSync\(/g) ?? []).length;
  const sourceClean = renameCount === 1 && !supSource.includes('.recovering-') &&
    supSource.includes('renameSync(tmp, this.ownershipLockPath)');
  check('O10', "auditor's three-process interleaving CLOSED: while A operates, B and C refuse pre-spawn (nothing dispatched, lock intact); supervision source has NO recovery-rename path (only the owner heartbeat replace)",
    rb.acquired === false && rc.acquired === false &&
      rb.code === 'COGNEE_STORE_OWNED' && rc.code === 'COGNEE_STORE_OWNED' &&
      servedByA === 1 && spawnsByA === 1 && receipt?.servedOps === 1 && lockIntact &&
      sourceClean,
    { b: rb, c: rc, aServed: servedByA, aSpawns: spawnsByA, lockIntact,
      renameSyncCount: renameCount, sourceClean }, Date.now() - t);
  await packI.supervision.shutdown();
}

// ---- O5: resource recording ---------------------------------------------------
{
  const stats = packA!.supervision.stats;
  check('O5', 'resource recording (single worker spawn under packA; refused ops never dispatch)',
    stats.spawns === 1 && stats.opsServed === 2, // search op + orderly shutdown op
    { ...stats, duration_s: Math.round((Date.now() - t0) / 1000) });
}

const out = {
  verification: 'c5-store-ownership-fail-closed',
  victAbiReference: 'radz2291/vict-02@5ea0afe257d5e7f67e050fcae169746a25fd3cc4 (read-only)',
  store: 'fresh (proof/.cognee-ownership + race/heartbeat sub-stores)',
  started: new Date(t0).toISOString(),
  duration_s: Math.round((Date.now() - t0) / 1000),
  results,
};
writeFileSync(path.join(repo, 'worker', 'c4-ownership-results.json'), JSON.stringify(out, null, 2));
console.error(`[own] COMPLETE ${out.duration_s}s — ` +
  `${results.filter((r) => r.outcome === 'PASS').length}/${results.length} PASS`);
// C5 (audit M1): failed assertions MUST produce a non-zero exit status.
process.exit(results.some((r) => r.outcome !== 'PASS') ? 1 : 0);
