/**
 * C4-exit ownership verification — exclusive store ownership at the
 * supervision layer (contract §3/§8; upstream gap: one pack instance
 * supervises one worker, but separate pack instances or separate PROCESSES
 * could point at the same Cognee root).
 *
 * Run (from repo root):
 *   ../260831-VCT-02/node_modules/.bin/tsx pack/verify/ownership-verify.ts
 *
 * Fresh disposable store (proof/.cognee-ownership, own .env):
 *  O1  first pack instance claims exclusive ownership (lock file, held);
 *  O2  a SECOND pack instance on the SAME store fails closed
 *      (COGNEE_STORE_OWNED) at construction — before any worker spawn;
 *  O2b a crafted lock belonging to a LIVE owner (live pid) fails closed and
 *      is NEVER deleted (lock bytes unchanged);
 *  O3  the owning instance runs a real worker op under ownership; orderly
 *      shutdown RELEASES ownership; a new instance acquires it (restart);
 *  O4  stale-owner recovery: a lock whose owner pid is verifiably DEAD is
 *      recovered (unlink + atomic re-create) by a new instance;
 *  O5  resource recording (spawns, ops, wall clock).
 */

import { writeFileSync, mkdirSync, rmSync, readFileSync, existsSync, unlinkSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { hostname } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createCogneePack, WorkerError } from '../src/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const STORE = path.join(repo, 'proof', '.cognee-ownership');
const PY = path.join(repo, 'proof', '.venv', 'Scripts', 'python.exe');
const NAMESPACES = ['qa'];

// ---- fresh disposable store -------------------------------------------------
for (let attempt = 0; ; attempt++) {
  try {
    rmSync(STORE, { recursive: true, force: true });
    break;
  } catch (e) {
    if (attempt >= 4) throw e;
    await new Promise((r) => setTimeout(r, 2_000));
  }
}
mkdirSync(path.join(STORE, 'system'), { recursive: true });
writeFileSync(path.join(STORE, '.env'), [
  '# Fresh disposable ownership-verification store (generated by ownership-verify.ts)',
  'ENV=dev', 'RUNTIME__LOG_LEVEL=INFO',
  ...Object.entries({
    SYSTEM_ROOT_DIRECTORY: 'system', DATA_ROOT_DIRECTORY: 'data',
    CACHE_ROOT_DIRECTORY: 'cache', LOGS_ROOT_DIRECTORY: 'logs',
    COGNEE_REPOS_DIR: 'repos',
  }).map(([k, v]) => `${k}=${path.join(STORE, v).replace(/\\/g, '/')}`),
  'VECTOR_DB_PROVIDER=lancedb', 'GRAPH_DATABASE_PROVIDER=ladybug',
  'DB_PROVIDER=sqlite', 'EMBEDDING_PROVIDER=fastembed',
  'EMBEDDING_MODEL=BAAI/bge-small-en-v1.5', 'EMBEDDING_DIMENSIONS=384',
  'GRAPH_EXTRACTOR=gliner_demo', 'AUTO_FEEDBACK=false', '',
].join('\n'));

const LOCK = path.join(STORE, 'cognee-store-owner.lock');
const t0 = Date.now();
const results: { id: string; name: string; outcome: string; detail?: unknown; ms?: number }[] = [];
function check(id: string, name: string, cond: boolean, detail?: unknown, ms?: number): boolean {
  results.push({ id, name, outcome: cond ? 'PASS' : 'FAIL', detail, ms });
  console.error(`[own] ${id} ${cond ? 'PASS' : 'FAIL'} ${name} ${ms !== undefined ? `(${ms}ms)` : ''}`);
  return cond;
}

function makePack(): ReturnType<typeof createCogneePack> {
  return createCogneePack({
    pythonPath: PY, cwd: STORE, storeRoot: STORE, namespaces: NAMESPACES,
    readyBudgetMs: 180_000,
    diag: (line) => console.error(`[own-sup] ${line.slice(0, 140)}`),
  });
}

// ---- O1: first instance claims exclusive ownership --------------------------
let packA: ReturnType<typeof createCogneePack> | null = null;
{
  const t = Date.now();
  try {
    packA = makePack();
    const rec = JSON.parse(readFileSync(LOCK, 'utf8')) as { pid?: number; instanceId?: string };
    check('O1', 'first instance claims exclusive store ownership (lock held, pid recorded)',
      packA.supervision.storeOwnershipHeld && rec.pid === process.pid &&
        typeof rec.instanceId === 'string',
      { lockPid: rec.pid, held: packA.supervision.storeOwnershipHeld }, Date.now() - t);
  } catch (e) {
    check('O1', 'first instance claims exclusive store ownership', false,
      { error: String(e) }, Date.now() - t);
    throw e;
  }
}

// ---- O2: second instance fails closed (pre-spawn) ----------------------------
{
  const t = Date.now();
  let refused: unknown = null;
  try { makePack(); } catch (e) { refused = e; }
  const we = refused instanceof WorkerError ? refused : null;
  check('O2', 'second pack instance on the SAME store fails closed (COGNEE_STORE_OWNED, pre-spawn)',
    we?.code === 'COGNEE_STORE_OWNED' && packA!.supervision.stats.spawns === 0,
    { code: we?.code ?? String(refused), spawns: packA!.supervision.stats.spawns },
    Date.now() - t);
}

// ---- O2b: a LIVE owner's lock is never deleted -------------------------------
{
  const t = Date.now();
  // Craft a lock owned by a LIVE process (a sleeping node child) with a
  // deliberately stale heartbeat — pid liveness must win over the heartbeat.
  const sleeper = spawn(process.execPath, ['-e', 'setInterval(()=>{},1e6)'], { stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 300));
  const crafted = JSON.stringify({
    schema: 'vict.cognee.store-ownership@1',
    instanceId: 'crafted-live-owner-0000',
    pid: sleeper.pid, host: hostname(),
    startedAt: new Date().toISOString(),
    heartbeatAt: new Date(Date.now() - 600_000).toISOString(),
  });
  writeFileSync(LOCK, crafted);
  let refused: unknown = null;
  try { makePack(); } catch (e) { refused = e; }
  const we = refused instanceof WorkerError ? refused : null;
  const unchanged = readFileSync(LOCK, 'utf8') === crafted;
  check('O2b', 'live owner lock (stale heartbeat, live pid) fails closed AND is never deleted',
    we?.code === 'COGNEE_STORE_OWNED' && unchanged,
    { code: we?.code ?? String(refused), lockUnchanged: unchanged }, Date.now() - t);
  sleeper.kill('SIGKILL');
  unlinkSync(LOCK); // harness cleanup of the CRAFTED lock (owner already verified live-protected)
}

// ---- O3: real op under ownership + orderly shutdown releases + restart -------
{
  const t = Date.now();
  // packA still holds ownership; its lock record was replaced by the crafted
  // lock in O2b and then removed — the next op's heartbeat refresh re-writes it.
  const searchBinding = packA!.bindings.capabilities.find((b) => b.id === 'cognee.searchChunks')!;
  try {
    await searchBinding.invoke({ datasets: ['qa.any'], query: 'warmup' }, { mode: 'normal' });
  } catch {
    // typed dataset-unknown/worker error is acceptable here: the point is
    // that the worker RAN under exclusive ownership (spawn + lock intact).
  }
  const ran = packA!.supervision.stats.spawns >= 1 && packA!.supervision.storeOwnershipHeld;
  check('O3a', 'worker op runs under held exclusive ownership (spawn + lock intact)',
    ran, { spawns: packA!.supervision.stats.spawns,
      held: packA!.supervision.storeOwnershipHeld }, Date.now() - t);
  const t2 = Date.now();
  await packA!.supervision.shutdown();
  check('O3b', 'orderly shutdown RELEASES ownership (lock gone)',
    !packA!.supervision.storeOwnershipHeld && !existsSync(LOCK),
    { held: packA!.supervision.storeOwnershipHeld }, Date.now() - t2);
  const t3 = Date.now();
  const packC = makePack();
  const reacquired = packC.supervision.storeOwnershipHeld && existsSync(LOCK);
  check('O3c', 'restart: a new instance acquires ownership after orderly release',
    reacquired, {}, Date.now() - t3);
  packC.supervision.releaseStoreOwnership();
}

// ---- O4: stale-owner recovery (dead pid) --------------------------------------
{
  const t = Date.now();
  const dead = spawn(process.execPath, ['-e', 'process.exit(0)'], { stdio: 'ignore' });
  const deadPid = dead.pid!;
  await new Promise((r) => {
    dead.on('exit', () => r(null));
    setTimeout(() => r(null), 5_000);
  });
  const crafted = JSON.stringify({
    schema: 'vict.cognee.store-ownership@1',
    instanceId: 'dead-owner-00000000',
    pid: deadPid, host: hostname(),
    startedAt: new Date(Date.now() - 3_600_000).toISOString(),
    heartbeatAt: new Date(Date.now() - 3_600_000).toISOString(),
  });
  writeFileSync(LOCK, crafted);
  const packD = makePack();
  check('O4', 'stale-owner recovery: dead-pid owner lock is recovered by a new instance',
    packD.supervision.storeOwnershipHeld, { deadPid }, Date.now() - t);
  packD.supervision.releaseStoreOwnership();
}

// ---- O5: resource recording ---------------------------------------------------
{
  const stats = packA!.supervision.stats;
  check('O5', 'resource recording (single worker spawn across ownership tests)',
    stats.spawns === 1 && stats.opsServed >= 1,
    { ...stats, duration_s: Math.round((Date.now() - t0) / 1000) });
}

const out = {
  verification: 'c4-exit-store-ownership',
  victAbiReference: 'radz2291/vict-02@5ea0afe257d5e7f67e050fcae169746a25fd3cc4 (read-only)',
  store: 'fresh (proof/.cognee-ownership)',
  started: new Date(t0).toISOString(),
  duration_s: Math.round((Date.now() - t0) / 1000),
  results,
};
writeFileSync(path.join(repo, 'worker', 'c4-ownership-results.json'), JSON.stringify(out, null, 2));
console.error(`[own] COMPLETE ${out.duration_s}s — ` +
  `${results.filter((r) => r.outcome === 'PASS').length}/${results.length} PASS`);
process.exit(0);