/**
 * C4 pack verification — @victframework/cognee through a REAL VICT runtime.
 *
 * Run (from repo root, VICT stays untouched — imports resolve read-only into
 * the local vict-02 clone):
 *   ../260831-VCT-02/node_modules/.bin/tsx pack/verify/verify.ts
 *
 * Proven here (disposable store proof/.cognee-verify, own .env + journal):
 *  V0 manifest validates (sdk validateCapabilityPack, victCompatibility ^0.1.0);
 *  V1 pack installs atomically into a real runtime (all six capabilities);
 *  V2 mode 'test': add/cognify run via DECLARED DOUBLES — zero worker spawns,
 *     contract-valid receipts, invokedVia = double;
 *  V3 mode 'test': read capability (searchChunks) has NO double => fail-closed
 *     block by the effect policy (real implementation unreachable);
 *  V4 runtime WITHOUT grants: write invocation fails BEFORE the handler
 *     (permission pre-check; no worker spawn, no cognee touch);
 *  V5 normal mode, REAL worker: graph decide -> add(keyed write, retry policy)
 *     -> cognify(keyed write) -> shape(pure) -> searchChunks(read) completes
 *     through the durable orchestration driver; receipts carry item counts;
 *     search returns in-scope hits;
 *  V6 binding-level keyed semantics: same key replays the known outcome with
 *     NO re-execution; reusing the key for different content throws
 *     COGNEE_IDEMPOTENCY_MISMATCH;
 *  V7 irreversible gating: forgetDataset in normal mode is denied by default;
 *     with run policy {allowIrreversible:true} it runs and files 2->0... (as
 *     observed: purged 'file-level');
 *  V9 C4-exit mode guard: DURABLE graphs (reads / add / cognify /
 *     forgetDataset) in test/simulate are refused by every real binding
 *     (COGNEE_MODE_REFUSED) — no worker spawn, no store change;
 *  V10 C4-exit deadlines: an expired or insufficient ctx.deadlineAt fails
 *     BEFORE the worker request (COGNEE_DEADLINE_EXCEEDED) and is never
 *     replaced with a fresh full timeout;
 *  V11 the pack resolves its OWN BUNDLED worker (no proof path) — the
 *     supervision default workerPath points into pack/src/worker/;
 *  V8 resource + environment recording (spawns, RSS, free RAM, durations).
 */

import { writeFileSync, mkdirSync, rmSync, readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// VICT ABI reference — read-only imports from the local vict-02 clone @ 5ea0afe2.
const VICT = 'file:///C:/Users/RZ1/Desktop/RZ/260831-VCT-02';
const { createRuntime, createInMemoryStores, installCapabilityPack } =
  await import(`${VICT}/packages/runtime/dist/index.js`);
const { validateCapabilityPack, neutralJsonContract } =
  await import(`${VICT}/packages/sdk/dist/index.js`);

import { createCogneePack, WorkerError, BindingRefusedError } from '../src/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const STORE = path.join(repo, 'proof', '.cognee-verify');
const PY = path.join(repo, 'proof', '.venv', 'Scripts', 'python.exe');
const NAMESPACES = ['qa'];

function freeRamGb(): number {
  try {
    const out = execSync('powershell -NoProfile -Command "(Get-CimInstance Win32_OperatingSystem).FreePhysicalMemory/1MB"',
      { encoding: 'utf8', timeout: 30_000 });
    return Math.round(parseFloat(out.trim()) * 100) / 100;
  } catch {
    return -1;
  }
}

// ---- fresh disposable store (one store / one worker / one trust domain) ------
for (let attempt = 0; ; attempt++) {
  try {
    rmSync(STORE, { recursive: true, force: true });
    break;
  } catch (e) {
    if (attempt >= 4) throw e;
    await new Promise((r) => setTimeout(r, 2_000));
  }
}
mkdirSync(path.join(STORE, 'system'), { recursive: true });
const envFile = [
  '# Fresh disposable verification store (generated by pack/verify/verify.ts)',
  'ENV=dev',
  'RUNTIME__LOG_LEVEL=INFO',
  ...Object.entries({
    SYSTEM_ROOT_DIRECTORY: 'system', DATA_ROOT_DIRECTORY: 'data',
    CACHE_ROOT_DIRECTORY: 'cache', LOGS_ROOT_DIRECTORY: 'logs',
    COGNEE_REPOS_DIR: 'repos',
  }).map(([k, v]) => `${k}=${path.join(STORE, v).replace(/\\/g, '/')}`),
  'VECTOR_DB_PROVIDER=lancedb',
  'GRAPH_DATABASE_PROVIDER=ladybug',
  'DB_PROVIDER=sqlite',
  'EMBEDDING_PROVIDER=fastembed',
  'EMBEDDING_MODEL=BAAI/bge-small-en-v1.5',
  'EMBEDDING_DIMENSIONS=384',
  'GRAPH_EXTRACTOR=gliner_demo',
  'AUTO_FEEDBACK=false',
  '',
].join('\n');
writeFileSync(path.join(STORE, '.env'), envFile);

const t0 = Date.now();
const ramStart = freeRamGb();
const results: { id: string; name: string; outcome: string; detail?: unknown; ms?: number }[] = [];
function record(id: string, name: string, outcome: string, detail?: unknown, ms?: number): void {
  results.push({ id, name, outcome, detail, ms });
  console.error(`[verify] ${id} ${outcome} ${name} ${ms !== undefined ? `(${ms}ms)` : ''}`);
}
function check(id: string, name: string, cond: boolean, detail?: unknown, ms?: number): boolean {
  record(id, name, cond ? 'PASS' : 'FAIL', detail, ms);
  return cond;
}

// ---- pack instance (one supervision => one live worker per store) -----------
// NOTE: no explicit workerPath — the pack MUST resolve its own BUNDLED worker
// (pack/src/worker/cognee_worker.py). V11 verifies that resolution.
const pack = createCogneePack({
  pythonPath: PY,
  cwd: STORE,
  storeRoot: STORE,
  namespaces: NAMESPACES,
  readyBudgetMs: 180_000,
  diag: (line) => console.error(`[sup] ${line.slice(0, 160)}`),
});

/** Store snapshot for no-store-change assertions (relative path + size). */
function storeSnapshot(): string[] {
  const files: string[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.isFile()) files.push(`${path.relative(STORE, p)}:${statSync(p).size}`);
    }
  };
  walk(STORE);
  return files.sort();
}

// ---- durable-driver graphs (decision node + node retry policies + timeouts =>
//      vict.activation@2: the runtime DERIVES idempotencyKeys for the write
//      nodes; the real binding always runs, even in test/simulate) -------------
const WRITE_GRAPH = {
  id: 'cognee-verify-write', entry: 'decide',
  nodes: [
    { id: 'decide', kind: 'decision', capability: 'cognee.verify.route' },
    { id: 'put', capability: 'cognee.add',
      retry: { maxAttempts: 2, retryOn: ['VICT_RUNTIME_CAPABILITY_THREW'],
        backoff: { kind: 'fixed', delayMs: 200 } },
      timeoutMs: 180_000, output: 'cognee.mutating-receipt' },
    { id: 'adapt', capability: 'cognee.verify.identity' },
    { id: 'graph', capability: 'cognee.cognify',
      retry: { maxAttempts: 2, retryOn: ['VICT_RUNTIME_CAPABILITY_THREW'],
        backoff: { kind: 'fixed', delayMs: 200 } },
      timeoutMs: 300_000, output: 'cognee.mutating-receipt' },
  ],
  edges: [
    { from: 'decide', to: 'put', kind: 'route', key: 'go' },
    { from: 'put', to: 'adapt' },
    { from: 'adapt', to: 'graph' },
  ],
};
const FORGET_GRAPH = {
  id: 'cognee-verify-forget', entry: 'decide',
  nodes: [
    { id: 'decide', kind: 'decision', capability: 'cognee.verify.route' },
    { id: 'adapt', capability: 'cognee.verify.identity' },
    { id: 'remove', capability: 'cognee.forgetDataset', timeoutMs: 120_000,
      output: 'cognee.forget-receipt' },
  ],
  edges: [
    { from: 'decide', to: 'adapt', kind: 'route', key: 'go' },
    { from: 'adapt', to: 'remove' },
  ],
};

// ---- harness capabilities (pure; graph glue only) ----------------------------
const routeContract = {
  id: 'verify.route-result', revision: '1',
  expected: '{ route: string, value: object }',
  parse: (input: unknown) => {
    const o = input as Record<string, unknown> | null;
    if (o && typeof o === 'object' && typeof o.route === 'string' &&
        typeof o.value === 'object') return { ok: true as const, value: o };
    return { ok: false as const, issues: [{ code: 'SHAPE', path: '$', message: 'expected { route, value }' }] };
  },
};
const neutralContract = {
  id: 'verify.neutral', revision: '1', expected: 'any object',
  parse: (input: unknown) => typeof input === 'object' && input !== null
    ? { ok: true as const, value: input }
    : { ok: false as const, issues: [{ code: 'SHAPE', path: '$', message: 'expected object' }] },
};

const routeCapability = {
  id: 'cognee.verify.route', revision: '1', effect: 'pure' as const,
  input: neutralContract, output: routeContract,
  invoke: (input: unknown) => ({ route: 'go', value: input }),
};
const shapeCapability = {
  id: 'cognee.verify.shape', revision: '1', effect: 'pure' as const,
  input: neutralJsonContract, output: neutralJsonContract,
  invoke: (input: unknown) => {
    const datasetName = (input as { datasetName?: string }).datasetName as string;
    return { datasets: [datasetName], query: 'settlement windows', topK: 5 };
  },
};
/** Pure identity adapter: bridges differing pack contract ids across an edge
 *  (graph authors compose capabilities through explicit adaptation nodes; the
 *  compiler bridges only via the neutral JSON contract). */
const identityCapability = {
  id: 'cognee.verify.identity', revision: '1', effect: 'pure' as const,
  input: neutralJsonContract, output: neutralJsonContract,
  invoke: (input: unknown) => input,
};

// ---- graphs ---------------------------------------------------------------
// ABI fact (verified, orchestration-driver.ts): the DURABLE orchestration
// engine always runs the pinned real binding — doubles are a Stage 02
// sequential-engine facility (capability-only graphs). Consequences:
//  - doubles (test/simulate) verify on capability-only graphs;
//  - real keyed cognee writes verify on the durable driver with node retry
//    policies (the runtime derives idempotencyKeys ONLY there);
//  - a capability-only graph in normal mode invokes the real binding WITHOUT
//    a context key — the binding must refuse it (unkeyed writes never run).
const DOUBLES_WRITE_GRAPH = {
  id: 'cognee-verify-doubles', entry: 'put',
  nodes: [
    { id: 'put', capability: 'cognee.add', output: 'cognee.mutating-receipt' },
    { id: 'adapt', capability: 'cognee.verify.identity' },
    { id: 'graph', capability: 'cognee.cognify', output: 'cognee.mutating-receipt' },
  ],
  edges: [{ from: 'put', to: 'adapt' }, { from: 'adapt', to: 'graph' }],
};
const FORGET_DOUBLE_GRAPH = {
  id: 'cognee-verify-forget-double', entry: 'remove',
  nodes: [
    { id: 'remove', capability: 'cognee.forgetDataset', output: 'cognee.forget-receipt' },
  ],
  edges: [],
};
const READ_GRAPH = {
  id: 'cognee-verify-read', entry: 'find',
  nodes: [
    // NOTE: no timeoutMs/retry here — any node with retry/timeoutMs (or any
    // control kind/route edge) flips the graph to the durable orchestration
    // engine (declaresControlSemantics, canonical.ts:185-201), which ALWAYS
    // invokes the real binding — test/simulate doubles are a sequential-engine
    // facility only. Read isolation (fail-closed without a double) is verified
    // on this deliberately capability-only graph.
    { id: 'find', capability: 'cognee.searchChunks',
      output: 'cognee.search-output' },
  ],
  edges: [],
};

function newRuntime(granted: boolean) {
  const runtime = createRuntime({
    stores: createInMemoryStores(),
    ...(granted ? { authority: { grants: ['cognee.write', 'cognee.search', 'cognee.delete'] } } : {}),
  });
  runtime.registerContract(neutralContract).registerContract(routeContract)
    .registerContract(neutralJsonContract as never);
  runtime.registerCapability(routeCapability as never)
    .registerCapability(shapeCapability as never)
    .registerCapability(identityCapability as never);
  return runtime;
}

// ---- V0: manifest validation --------------------------------------------------
{
  const t = Date.now();
  const validation = validateCapabilityPack(pack as never, { victVersion: '0.1.0' });
  check('V0', 'manifest validates (vict.capability-pack@1, ^0.1.0)',
    validation.ok === true, validation.ok ? { capabilities: pack.manifest.capabilities.length } : validation.issues, Date.now() - t);
}

// ---- V1: atomic installation ---------------------------------------------------
const runtimeGranted = newRuntime(true);
{
  const t = Date.now();
  try {
    const { installed } = installCapabilityPack(runtimeGranted, pack as never);
    check('V1', 'installCapabilityPack installs all six capabilities atomically',
      installed.length === 6, { installed: [...installed] }, Date.now() - t);
  } catch (e) {
    check('V1', 'installCapabilityPack installs all six capabilities atomically', false,
      { error: String(e) }, Date.now() - t);
  }
}

// ---- V2: test-mode doubles on the SEQUENTIAL engine (zero cognee/store touch)
{
  const t = Date.now();
  const activated = await runtimeGranted.activate(DOUBLES_WRITE_GRAPH as never);
  if (!activated.ok) {
    check('V2', 'test-mode run via doubles', false,
      { issues: activated.issues.map((i: { code: string }) => i.code) }, Date.now() - t);
  } else {
    const spawnsBefore = pack.supervision.stats.spawns;
    const run = await runtimeGranted.run(
      { datasetName: 'qa.verify', content: 'C4VERIFY marker: test-mode doubles never touch cognee.' },
      { mode: 'test' });
    const receipt = run.output as { datasetName?: string; itemsAfter?: number; reconciled?: string };
    check('V2', 'test-mode run completes via declared doubles (add+cognify)',
      run.status === 'completed' && receipt?.datasetName === 'qa.verify' &&
        receipt?.itemsAfter === 1 && pack.supervision.stats.spawns === spawnsBefore,
      { status: run.status, output: receipt, spawns: pack.supervision.stats.spawns }, Date.now() - t);
  }
}

// ---- V2b: forget double in test mode (sequential engine) -------------------------
{
  const t = Date.now();
  const activated = await runtimeGranted.activate(FORGET_DOUBLE_GRAPH as never);
  if (!activated.ok) {
    check('V2b', 'forget double in test mode', false,
      { issues: activated.issues.map((i: { code: string }) => i.code) }, Date.now() - t);
  } else {
    const spawnsBefore = pack.supervision.stats.spawns;
    const run = await runtimeGranted.run({ datasetName: 'qa.never-existed' }, { mode: 'test' });
    const receipt = run.output as { datasetName?: string; datasetId?: string; purged?: string };
    check('V2b', 'forget double runs in test mode (no real store touch)',
      run.status === 'completed' && receipt?.datasetId === 'double-dataset-id' &&
        pack.supervision.stats.spawns === spawnsBefore,
      { status: run.status, output: receipt }, Date.now() - t);
  }
}

// ---- V3: read in test mode => fail-closed (no double declared; sequential engine)
{
  const t = Date.now();
  const activated = await runtimeGranted.activate(READ_GRAPH as never);
  if (!activated.ok) {
    check('V3', 'read in test mode fails closed (no double)', false,
      { issues: activated.issues.map((i: { code: string }) => i.code) }, Date.now() - t);
  } else {
    const spawnsBefore = pack.supervision.stats.spawns;
    const run = await runtimeGranted.run(
      { datasets: ['qa.verify'], query: 'settlement windows' }, { mode: 'test' });
    // Blocked runs surface 'blocked' status (error stays null — the reason
    // lives in events); the decisive check is: not completed, no real spawn.
    check('V3', 'read in test mode fails closed (no double declared)',
      run.status === 'blocked' && pack.supervision.stats.spawns === spawnsBefore,
      { status: run.status, spawns: pack.supervision.stats.spawns, spawnsBefore },
      Date.now() - t);
  }
}

// ABI OBSERVATION (updated by the C4 exit corrections): a graph whose nodes
// carry retry/timeoutMs (or control kinds / route edges) compiles to
// vict.activation@2 and runs on the DURABLE orchestration engine, which
// ALWAYS invokes the pinned REAL binding — even in 'test'/'simulate' modes
// (upstream VICT issue UV-1, docs/upstream-vict-issues.md). Consequence for
// this pack: every real binding FAILS CLOSED unless ctx.mode === 'normal'
// (V9), so durable graphs can no longer touch the worker/store outside
// normal mode; VICT-side durable graphs for OTHER packs remain affected.
record('ABI', 'durable engine runs real bindings in test/simulate; pack bindings fail closed (UV-1)',
  'OBSERVATION', {
    source: 'orchestration-driver.ts (~line 702) + canonical.ts declaresControlSemantics; pack guard: bindings.ts requireNormalMode',
    consequence: 'mode isolation restored at the pack boundary; upstream durable graphs (other packs) still affected',
  });

// ---- V4: permission pre-check (ungranted runtime, handler never invoked) --------
{
  const t = Date.now();
  const runtimeUngranted = newRuntime(false);
  installCapabilityPack(runtimeUngranted, pack as never);
  const activated = await runtimeUngranted.activate(WRITE_GRAPH as never);
  if (!activated.ok) {
    check('V4', 'ungranted write fails pre-handler (permission denied, no cognee)', false,
      { issues: activated.issues.map((i: { code: string }) => i.code) }, Date.now() - t);
  } else {
  const spawnsBefore = pack.supervision.stats.spawns;
  const run = await runtimeUngranted.run(
    { datasetName: 'qa.verify', content: 'must never run' }, { mode: 'normal' });
  const msg = JSON.stringify(run.error ?? run).toLowerCase();
  check('V4', 'ungranted write fails pre-handler (permission denied, no cognee)',
    run.status !== 'completed' && msg.includes('permission') &&
      pack.supervision.stats.spawns === spawnsBefore,
    { status: run.status, error: run.error ?? null }, Date.now() - t);
  }
}

// ---- V5: normal mode, REAL worker, durable orchestration driver ------------------
const qaDoc = 'Quellight C3QA marker: settlement windows close at 17:00 local time; ' +
  'ledger reconciliation runs nightly under dual approval; exceptions escalate ' +
  'to the on-call settlement controller before the next business day.';
{
  const t = Date.now();
  await runtimeGranted.activate(WRITE_GRAPH as never);
  const run = await runtimeGranted.run(
    { datasetName: 'qa.verify', content: qaDoc }, { mode: 'normal' });
  const receipt = run.output as { datasetName?: string; itemsAfter?: number; reconciled?: string };
  if (!check('V5', 'normal-mode keyed write graph completes through real worker',
    run.status === 'completed' && receipt?.itemsAfter === 1,
    { status: run.status, output: receipt, error: run.error ?? null,
      spawns: pack.supervision.stats.spawns }, Date.now() - t)) {
    throw new Error('V5 write graph failed — aborting (nothing else can run without the store)');
  }
  const t2 = Date.now();
  const readActivated = await runtimeGranted.activate(READ_GRAPH as never);
  if (readActivated.ok) {
    const run2 = await runtimeGranted.run(
      { datasets: ['qa.verify'], query: 'settlement windows' }, { mode: 'normal' });
    const search = run2.output as { total?: number; hits?: { datasetName?: string }[] };
    check('V5', 'normal-mode scoped search returns in-scope hits',
      run2.status === 'completed' && (search?.total ?? 0) > 0 &&
        search?.hits?.[0]?.datasetName === 'qa.verify',
      { status: run2.status, total: search?.total, first: search?.hits?.[0] }, Date.now() - t2);
  } else {
    check('V5', 'normal-mode scoped search returns in-scope hits', false,
      { issues: readActivated.issues.map((i: { code: string }) => i.code) }, Date.now() - t2);
  }
}

// ---- V5b: sequential-engine write in NORMAL mode refused (unkeyed, no ctx key) ---
{
  const t = Date.now();
  const spawnsBefore = pack.supervision.stats.spawns;
  const activated = await runtimeGranted.activate(DOUBLES_WRITE_GRAPH as never);
  if (!activated.ok) {
    check('V5b', 'sequential-engine write refused (no CapabilityContext key)', false,
      { issues: activated.issues.map((i: { code: string }) => i.code) }, Date.now() - t);
  } else {
    const spawnsBefore = pack.supervision.stats.spawns;
    const run = await runtimeGranted.run(
      { datasetName: 'qa.verify', content: 'must be refused: unkeyed' }, { mode: 'normal' });
    const msg = JSON.stringify(run.error ?? run).toLowerCase();
    check('V5b', 'sequential-engine write refused (no CapabilityContext key)',
      run.status !== 'completed' &&
        (msg.includes('threw') || msg.includes('idempotencykey')) &&
        pack.supervision.stats.spawns === spawnsBefore,
      // the real binding refuses in-process before any cognee call or spawn
      { status: run.status, error: run.error ?? null }, Date.now() - t);
  }
}

// ---- V6: binding-level keyed semantics (same worker, single-owner) ---------------
{
  const t = Date.now();
  const addBinding = pack.bindings.capabilities.find((b) => b.id === 'cognee.add')!;
  const ctx = { mode: 'normal', idempotencyKey: 'verify-k1', attemptNumber: 1 };
  const first = await addBinding.invoke(
    { datasetName: 'qa.binding', content: 'C4BINDING marker: keyed replay at the binding layer.' },
    ctx) as { reconciled?: string; itemsAfter?: number };
  const replay = await addBinding.invoke(
    { datasetName: 'qa.binding', content: 'C4BINDING marker: keyed replay at the binding layer.' },
    ctx) as { reconciled?: string; itemsAfter?: number };
  check('V6', 'same key replays known outcome without re-execution',
    first.reconciled === 'fresh-execution' && first.itemsAfter === 1 &&
      replay.reconciled === 'replayed-known-outcome' && replay.itemsAfter === 1,
    { first: first.reconciled, replay: replay.reconciled }, Date.now() - t);
  const t2 = Date.now();
  let mismatch: unknown = null;
  try {
    await addBinding.invoke(
      { datasetName: 'qa.binding', content: 'DIFFERENT CONTENT under the same key' }, ctx);
  } catch (e) {
    mismatch = e;
  }
  check('V6', 'same key + different content rejected (COGNEE_IDEMPOTENCY_MISMATCH)',
    mismatch instanceof WorkerError && mismatch.code === 'COGNEE_IDEMPOTENCY_MISMATCH',
    { got: mismatch instanceof WorkerError ? mismatch.code : String(mismatch) }, Date.now() - t2);
  const t3 = Date.now();
  const cogBinding = pack.bindings.capabilities.find((b) => b.id === 'cognee.cognify')!;
  const cogReceipt = await cogBinding.invoke({ datasetName: 'qa.binding' },
    { mode: 'normal', idempotencyKey: 'verify-k2' }) as { itemsAfter?: number };
  check('V6', 'cognify via binding key (real graph for V7 forget)',
    cogReceipt.itemsAfter === 1, { itemsAfter: cogReceipt.itemsAfter }, Date.now() - t3);
}

// ---- V7: irreversible gating (denied by default; allowed by run policy) ----------
{
  const t = Date.now();
  await runtimeGranted.activate(FORGET_GRAPH as never);
  const spawnsBefore = pack.supervision.stats.spawns;
  const denied = await runtimeGranted.run({ datasetName: 'qa.binding' }, { mode: 'normal' });
  const deniedMsg = JSON.stringify(denied.error ?? denied).toLowerCase();
  check('V7', 'forget denied by default in normal mode (allowIrreversible gate)',
    denied.status !== 'completed' &&
      (deniedMsg.includes('irreversible') || deniedMsg.includes('double')) &&
      pack.supervision.stats.spawns === spawnsBefore,
    { status: denied.status, error: denied.error ?? null }, Date.now() - t);
  const t2 = Date.now();
  const allowed = await runtimeGranted.run({ datasetName: 'qa.binding' },
    { mode: 'normal', policy: { allowIrreversible: true } });
  const receipt = allowed.output as { datasetName?: string; purged?: string;
    storeFilesBefore?: number; storeFilesAfter?: number };
  check('V7', 'forget with allowIrreversible runs for real (file-level purge receipt)',
    allowed.status === 'completed' && receipt?.purged === 'file-level' &&
      receipt?.storeFilesAfter === 0,
    { status: allowed.status, receipt }, Date.now() - t2);
}

// ---- V9: C4-exit mode guard — durable graphs NEVER reach the real worker in
// test/simulate (upstream VICT issue UV-1: the durable engine ignores
// useDouble; the pack fails closed at every real binding) --------------------
const DURABLE_READ_GRAPH = {
  id: 'cognee-verify-durable-read', entry: 'find',
  nodes: [
    { id: 'find', capability: 'cognee.searchChunks', timeoutMs: 60_000,
      output: 'cognee.search-output' },
  ],
  edges: [],
};
{
  const storeBefore = storeSnapshot();
  const spawnsBefore = pack.supervision.stats.spawns;
  // (a) durable WRITE graph (add+cognify) in 'test'
  {
    const t = Date.now();
    await runtimeGranted.activate(WRITE_GRAPH as never);
    const run = await runtimeGranted.run(
      { datasetName: 'qa.never', content: 'durable test-mode write must be refused' },
      { mode: 'test' });
    check('V9a', 'durable write graph in test mode refused (no worker spawn, no store change)',
      run.status !== 'completed' && run.status !== 'blocked' &&
        pack.supervision.stats.spawns === spawnsBefore &&
        JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore),
      { status: run.status, spawns: pack.supervision.stats.spawns,
        storeUnchanged: JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore) },
      Date.now() - t);
  }
  // (b) durable WRITE graph in 'simulate'
  {
    const t = Date.now();
    const run = await runtimeGranted.run(
      { datasetName: 'qa.never', content: 'durable simulate-mode write must be refused' },
      { mode: 'simulate' });
    check('V9b', 'durable write graph in simulate mode refused (no worker spawn, no store change)',
      run.status !== 'completed' && run.status !== 'blocked' &&
        pack.supervision.stats.spawns === spawnsBefore &&
        JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore),
      { status: run.status }, Date.now() - t);
  }
  // (c) durable READ graph in 'test'
  {
    const t = Date.now();
    const activated = await runtimeGranted.activate(DURABLE_READ_GRAPH as never);
    if (!activated.ok) {
      check('V9c', 'durable read graph in test mode refused', false,
        { issues: activated.issues.map((i: { code: string }) => i.code) }, Date.now() - t);
    } else {
      const run = await runtimeGranted.run(
        { datasets: ['qa.verify'], query: 'settlement windows' }, { mode: 'test' });
      check('V9c', 'durable read graph in test mode refused (no worker spawn, no store change)',
        run.status !== 'completed' && run.status !== 'blocked' &&
          pack.supervision.stats.spawns === spawnsBefore &&
          JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore),
        { status: run.status }, Date.now() - t);
    }
  }
  // (d) durable forgetDataset graph in 'test' — the irreversible denial does
  // NOT fire in test mode (decision.allowed=true, useDouble ignored), so this
  // real binding's own mode guard is the ONLY protection against a real purge.
  {
    const t = Date.now();
    await runtimeGranted.activate(FORGET_GRAPH as never);
    const run = await runtimeGranted.run({ datasetName: 'qa.verify' }, { mode: 'test' });
    check('V9d', 'durable forgetDataset graph in test mode refused (real purge unreachable)',
      run.status !== 'completed' && run.status !== 'blocked' &&
        pack.supervision.stats.spawns === spawnsBefore &&
        JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore),
      { status: run.status }, Date.now() - t);
  }
}

// ---- V10: C4-exit deadlines — expired/insufficient ctx.deadlineAt fails
// BEFORE the worker request; never re-armed with a fresh full timeout --------
{
  const spawnsBefore = pack.supervision.stats.spawns;
  const storeBefore = storeSnapshot();
  const addBinding = pack.bindings.capabilities.find((b) => b.id === 'cognee.add')!;
  // (a) already expired
  {
    const t = Date.now();
    let refused: unknown = null;
    try {
      await addBinding.invoke(
        { datasetName: 'qa.deadline', content: 'expired deadline must never run' },
        { mode: 'normal', idempotencyKey: 'verify-deadline-1', deadlineAt: Date.now() - 1_000 });
    } catch (e) { refused = e; }
    check('V10a', 'expired ctx.deadlineAt fails BEFORE the worker request',
      refused instanceof BindingRefusedError &&
        (refused as BindingRefusedError).code === 'COGNEE_DEADLINE_EXCEEDED' &&
        pack.supervision.stats.spawns === spawnsBefore &&
        JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore),
      { code: refused instanceof Error ? (refused as BindingRefusedError).code ?? refused.name : String(refused) },
      Date.now() - t);
  }
  // (b) insufficient remaining time (would be silently re-armed before)
  {
    const t = Date.now();
    let refused: unknown = null;
    try {
      await addBinding.invoke(
        { datasetName: 'qa.deadline', content: 'insufficient deadline must never run' },
        { mode: 'normal', idempotencyKey: 'verify-deadline-2', deadlineAt: Date.now() + 100 });
    } catch (e) { refused = e; }
    check('V10b', 'insufficient ctx.deadlineAt fails BEFORE the worker request (no fresh timeout)',
      refused instanceof BindingRefusedError &&
        (refused as BindingRefusedError).code === 'COGNEE_DEADLINE_EXCEEDED' &&
        pack.supervision.stats.spawns === spawnsBefore &&
        JSON.stringify(storeSnapshot()) === JSON.stringify(storeBefore),
      { code: refused instanceof Error ? (refused as BindingRefusedError).code ?? refused.name : String(refused) },
      Date.now() - t);
  }
  // (c) a read deadline is honored the same way
  {
    const t = Date.now();
    let refused: unknown = null;
    try {
      const readBinding = pack.bindings.capabilities.find((b) => b.id === 'cognee.searchChunks')!;
      await readBinding.invoke(
        { datasets: ['qa.verify'], query: 'x' },
        { mode: 'normal', deadlineAt: Date.now() - 5_000 });
    } catch (e) { refused = e; }
    check('V10c', 'expired deadline on a read fails before the worker request',
      refused instanceof BindingRefusedError &&
        (refused as BindingRefusedError).code === 'COGNEE_DEADLINE_EXCEEDED',
      {}, Date.now() - t);
  }
}

// ---- V10d-f: deadline honored through STARTUP and QUEUEING (deterministic,
// supervision-level, protocol stub worker; the real-runtime entry refusals
// above are V10a-c) -----------------------------------------------------------
// A protocol stub worker (pack/verify/stub_worker.py) with artificial delays:
//   V10d delayed worker startup (ready after 2.5 s; deadline 1 s) — must fail
//       BEFORE dispatch: nothing is ever sent (stub servedOps stays 0);
//   V10e queued request: op 1 occupies the worker (3 s), op 2 queued with a
//       1 s deadline — op 2 must fail BEFORE dispatch while queued;
//   V10f post-dispatch expiry: mutation dispatched with 0.8 s deadline, stub
//       replies after 3 s — outcome must be UNKNOWN (COGNEE_WRITE_UNKNOWN);
//       a read reports a clean typed failure (CLIENT_DEADLINE).
const STUB_STORE = path.join(repo, 'proof', '.cognee-verify-stub');
const STUB = path.join(here, 'stub_worker.py');
{
  for (let attempt = 0; ; attempt++) {
    try { rmSync(STUB_STORE, { recursive: true, force: true }); break; }
    catch { if (attempt >= 4) throw new Error(`cannot clear ${STUB_STORE}`); await new Promise((r) => setTimeout(r, 2_000)); }
  }
  mkdirSync(STUB_STORE, { recursive: true });
  // Instance D: delayed READY (deadline expiry during startup).
  const supD = createCogneePack({
    pythonPath: PY, cwd: STUB_STORE, storeRoot: STUB_STORE, namespaces: ['qa'],
    workerPath: STUB, readyBudgetMs: 60_000,
    env: { STUB_READY_DELAY_MS: '2500' },
    diag: (line) => console.error(`[stub-D] ${line.slice(0, 140)}`),
  }).supervision;
  try {
    const t = Date.now();
    let refused: unknown = null;
    try {
      await supD.request('add', { datasetName: 'qa.stub', content: 'x' },
        { mutating: true, deadlineAt: Date.now() + 1_000 });
    } catch (e) { refused = e; }
    const we = refused instanceof WorkerError ? refused : null;
    // Follow-up with a generous deadline proves NOTHING besides the probe
    // itself was dispatched (the stub counts every request it RECEIVES;
    // servedOps === 1 means exactly one request — the probe — reached it).
    const probe = await supD.request('datasets_status', {},
      { deadlineMs: 10_000 }) as { servedOps?: number };
    check('V10d', 'deadline expiring during worker startup fails BEFORE dispatch (no effect; only the probe itself was served)',
      we?.code === 'COGNEE_DEADLINE_EXCEEDED' && probe?.servedOps === 1,
      { code: we?.code ?? String(refused), servedOps: probe?.servedOps }, Date.now() - t);
  } finally {
    await supD.shutdown();
  }
  // Instance E: per-op delay for the slow ops (queueing + post-dispatch expiry).
  const supE = createCogneePack({
    pythonPath: PY, cwd: STUB_STORE, storeRoot: STUB_STORE, namespaces: ['qa'],
    workerPath: STUB, readyBudgetMs: 60_000,
    env: { STUB_DELAY_OPS: 'slow_op,slow_mutation,slow_read', STUB_DELAY_MS: '3000' },
    diag: (line) => console.error(`[stub-E] ${line.slice(0, 140)}`),
  }).supervision;
  try {
    // V10e: queued request's deadline expires while the worker is occupied.
    {
      const t = Date.now();
      const first = supE.request('slow_op', { marker: 'occupying' },
        { mutating: true, deadlineAt: Date.now() + 30_000 });
      // Wait until op 1 is dispatched, then enqueue op 2 with a 1 s deadline.
      await new Promise((r) => setTimeout(r, 300));
      let refused2: unknown = null;
      try {
        await supE.request('queued_op', { marker: 'queued' },
          { mutating: true, deadlineAt: Date.now() + 1_000 });
      } catch (e) { refused2 = e; }
      const we2 = refused2 instanceof WorkerError ? refused2 : null;
      const receipt = await first as { servedOps?: number };
      const probe = await supE.request('datasets_status', {},
        { deadlineMs: 10_000 }) as { servedOps?: number };
      // servedOps after probe: op1 + probe = 2 — queued_op was NEVER dispatched.
      check('V10e', 'queued request whose deadline expires while queued fails BEFORE dispatch (never sent)',
        we2?.code === 'COGNEE_DEADLINE_EXCEEDED' &&
          receipt?.servedOps === 1 && probe?.servedOps === 2,
        { code: we2?.code ?? String(refused2), op1: receipt?.servedOps,
          probeServed: probe?.servedOps }, Date.now() - t);
    }
    // V10f: deadline expires AFTER a mutation was dispatched => UNKNOWN.
    {
      const t = Date.now();
      let timedOut: unknown = null;
      try {
        await supE.request('slow_mutation', { marker: 'mut' },
          { mutating: true, deadlineAt: Date.now() + 800 });
      } catch (e) { timedOut = e; }
      const we = timedOut instanceof WorkerError ? timedOut : null;
      check('V10f', 'deadline expiring AFTER a mutation was dispatched reports UNKNOWN outcome (COGNEE_WRITE_UNKNOWN)',
        we?.code === 'COGNEE_WRITE_UNKNOWN',
        { code: we?.code ?? String(timedOut), detail: we?.detail }, Date.now() - t);
      // read variant: clean typed failure, not unknown
      const t2 = Date.now();
      let readTimeout: unknown = null;
      try {
        await supE.request('slow_read', { marker: 'read' },
          { mutating: false, deadlineAt: Date.now() + 800 });
      } catch (e) { readTimeout = e; }
      const rw = readTimeout instanceof WorkerError ? readTimeout : null;
      check('V10f', 'deadline expiring after a READ was dispatched reports a clean typed failure (CLIENT_DEADLINE)',
        rw?.code === 'CLIENT_DEADLINE',
        { code: rw?.code ?? String(readTimeout) }, Date.now() - t2);
    }
  } finally {
    await supE.shutdown();
  }
}

// ---- V11: the pack resolves its OWN BUNDLED worker (distributable surface) ----
{
  const t = Date.now();
  const wp = pack.supervision.workerPath;
  const normalized = wp.replace(/\\/g, '/');
  let workerSource = '';
  try { workerSource = readFileSync(wp, 'utf8'); } catch { /* missing */ }
  check('V11', 'pack resolves its OWN BUNDLED worker (no proof path; C4_FAULT absent)',
    normalized.includes('pack/src/worker/cognee_worker.py') && existsSync(wp) &&
      !workerSource.includes('C4_FAULT'),
    { workerPath: normalized, faultHookAbsent: !workerSource.includes('C4_FAULT') },
    Date.now() - t);
}

await pack.supervision.shutdown();

const ramEnd = freeRamGb();
const out = {
  verification: 'c4-pack-through-real-runtime',
  victAbiReference: 'radz2291/vict-02@5ea0afe257d5e7f67e050fcae169746a25fd3cc4 (read-only)',
  store: 'fresh (proof/.cognee-verify)',
  started: new Date(t0).toISOString(),
  duration_s: Math.round((Date.now() - t0) / 1000),
  environment: {
    freeRamGbStart: ramStart, freeRamGbEnd: ramEnd,
    note: 'Windows low-memory class: cognee cognify peaks ~2.0 GB; native crashes (0xC0000005) were observed in earlier batteries when free RAM dropped near 1.9 GB (agent observations, C1/C2). None occurred in this run; the supervision poison+respawn policy contains worker deaths as COGNEE_WRITE_UNKNOWN/COGNEE_WORKER_UNAVAILABLE.',
  },
  supervisionStats: pack.supervision.stats,
  results,
};
writeFileSync(path.join(repo, 'worker', 'c4-verify-results.json'), JSON.stringify(out, null, 2));
console.error(`[verify] COMPLETE ${out.duration_s}s — ` +
  `${results.filter((r) => r.outcome === 'PASS').length}/${results.length} PASS`);
process.exit(0);