/**
 * C3 proof driver v2 — hardened worker vs corrected pack contract, FRESH store.
 *
 * Corrections tested here (docs/c3-pack-contract.md correction pass):
 *  - one worker / one store / one trust domain: every run gets a FRESH
 *    disposable store (proof/.cognee-c3) built from its own .env;
 *  - datasetsStatus is scope-filtered: pre-existing datasets OUTSIDE the
 *    permitted domain (seeded first: legacy_unscoped, outside.vault) are
 *    never revealed, and addressing them is rejected;
 *  - durable keyed reconciliation with the VICT idempotencyKey for add and
 *    cognify: replay known outcomes, re-execute after interruption with
 *    item-level counts, dedupe convergence; forgetDataset has no journal and
 *    no auto-retry;
 *  - summary isolation with BOTH sides populated.
 * Worker death with a pending mutation stays an unknown outcome
 * (COGNEE_WRITE_UNKNOWN + poison + respawn); crashes are AGENT-OBSERVATIONs.
 * Results: worker/c3-results.json; diagnostics: worker/c3.log (stderr).
 */

import { WorkerClient, WorkerError } from './client.mjs';
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..');
const FRESH = path.join(repo, 'proof', '.cognee-c3');
const PY = path.join(repo, 'proof', '.venv', 'Scripts', 'python.exe');
const NAMESPACES = ['qa', 'zeta'];

// ---- fresh disposable store -------------------------------------------------
for (let attempt = 0; ; attempt++) {
  try {
    rmSync(FRESH, { recursive: true, force: true });
    break;
  } catch (e) {
    if (attempt >= 4) throw e;
    await new Promise((r) => setTimeout(r, 2_000)); // transient EBUSY (Windows)
  }
}
mkdirSync(path.join(FRESH, 'system'), { recursive: true });
const freshRoots = ['system', 'data', 'cache', 'logs', 'repos'];
const envFile = [
  '# Fresh disposable C3 store (generated by worker/proof_c3.mjs — safe to delete)',
  'ENV=dev',
  'RUNTIME__LOG_LEVEL=INFO',
  ...freshRoots.map((r) => {
    const key = { system: 'SYSTEM_ROOT_DIRECTORY', data: 'DATA_ROOT_DIRECTORY',
      cache: 'CACHE_ROOT_DIRECTORY', logs: 'LOGS_ROOT_DIRECTORY',
      repos: 'COGNEE_REPOS_DIR' }[r];
    return `${key}=${path.join(FRESH, r).replace(/\\/g, '/')}`;
  }),
  'VECTOR_DB_PROVIDER=lancedb',
  'GRAPH_DATABASE_PROVIDER=ladybug',
  'DB_PROVIDER=sqlite',
  'EMBEDDING_PROVIDER=fastembed',
  'EMBEDDING_MODEL=BAAI/bge-small-en-v1.5',
  'EMBEDDING_DIMENSIONS=384',
  'GRAPH_EXTRACTOR=gliner_demo',
  'AUTO_FEEDBACK=false',
  '',
].join('\n');
writeFileSync(path.join(FRESH, '.env'), envFile);

// ---- seed pre-existing datasets OUTSIDE the permitted domain ----------------
{
  const t = Date.now();
  const seed = spawnSync(PY, [path.join(repo, 'proof', 'c3_seed_foreign.py')],
    { cwd: FRESH, encoding: 'utf8', timeout: 300_000 });
  const ok = seed.status === 0;
  console.error(`[proof] seed ${ok ? 'ok' : 'FAILED'} (${Date.now() - t}ms)`);
  if (!ok) {
    console.error(String(seed.stderr || '').slice(-2000));
    writeFileSync(path.join(here, 'c3-results.json'), JSON.stringify({
      proof: 'c3-worker-contract', error: 'seed failed',
      started: new Date().toISOString(), results: [],
    }, null, 2));
    process.exit(1);
  }
}

const results = [];
const t0 = Date.now();

function record(id, name, outcome, detail, ms) {
  results.push({ id, name, outcome, detail, ms });
  console.error(`[proof] ${id} ${outcome} ${name} ${ms ? `(${ms}ms)` : ''}`);
}

function expectError(fn, code, label) {
  const t = Date.now();
  return fn().then(
    () => record(label.id, label.name, 'FAIL-EXPECTED-ERROR', { got: 'success' }, Date.now() - t),
    (e) => record(label.id, label.name,
      e.code === code ? 'PASS' : `FAIL-WRONG-CODE(${e.code})`,
      { expected: code, got: `${e.code}: ${String(e.message).slice(0, 140)}` },
      Date.now() - t));
}

const client = new WorkerClient(PY, path.join(here, 'worker.py'),
  { cwd: FRESH, namespaces: NAMESPACES, readyBudgetMs: 180_000,
    storeRoot: FRESH, diag: (m) => console.error(m) });

const OBS_CODES = ['COGNEE_WORKER_UNAVAILABLE', 'COGNEE_WRITE_UNKNOWN', 'CLIENT_DEADLINE'];

async function scenario(id, name, fn) {
  const t = Date.now();
  try {
    await fn();
  } catch (e) {
    record(id, name, OBS_CODES.includes(e.code) ? 'AGENT-OBSERVATION' : 'ERROR',
      { code: e.code ?? '?', message: String(e.message ?? e).slice(0, 220) },
      Date.now() - t);
    try { await client._lifecycle(); } catch { /* respawn best-effort */ }
  }
}

const qaDoc = 'Quellight C3QA marker: settlement windows close at 17:00 local time; ' +
  'ledger reconciliation runs nightly under dual approval; exceptions escalate ' +
  'to the on-call settlement controller before the next business day.';
const zetaDoc = 'Trading OS C3ZETA marker: the order router rebalances inventory ' +
  'positions at the 09:30 open; fills above the notional band require a second ' +
  'approver before the rebalance is published to the trading journal.';
const delayDoc = 'C3DELAY marker paragraph. '.repeat(19_000); // ~494 KB, valid

await scenario('s1', 'startup guard + ready (fresh store)', async () => {
  const t = Date.now();
  const ready = await client.ensureReady();
  const correctStore = String(ready.store_root).startsWith(FRESH);
  record('s1', 'startup guard + ready (fresh store)',
    ready.allowed_namespaces && correctStore ? 'PASS' : 'FAIL',
    { protocol: ready.protocol, import_ms: ready.import_ms,
      namespaces: ready.allowed_namespaces, storeRoot: ready.store_root,
      rss_mb: Math.round(ready.rss_bytes / 1e6) }, Date.now() - t);
});

await scenario('s2', 'fresh-execution + replay + search (qa.alpha)', async () => {
  const t = Date.now();
  const add1 = await client.request('add',
    { datasetName: 'qa.alpha', content: qaDoc, idempotencyKey: 'k-qa-alpha-1' },
    { mutating: true, deadlineMs: 120_000 });
  record('s2', 'add fresh-execution with item counts',
    add1.reconciled === 'fresh-execution' && add1.itemsAfter === 1 ? 'PASS' : 'FAIL',
    add1, Date.now() - t);
  const t2 = Date.now();
  const add2 = await client.request('add',
    { datasetName: 'qa.alpha', content: qaDoc, idempotencyKey: 'k-qa-alpha-1' },
    { mutating: true, deadlineMs: 60_000 });
  record('s2', 'same key replays known outcome (no re-exec)',
    add2.reconciled === 'replayed-known-outcome' && add2.itemsAfter === 1
      ? 'PASS' : 'FAIL', add2, Date.now() - t2);
  const t3 = Date.now();
  await client.request('cognify',
    { datasetName: 'qa.alpha', idempotencyKey: 'k-qa-alpha-c1' },
    { mutating: true, deadlineMs: 240_000 });
  const hits = await client.request('search_chunks',
    { datasets: ['qa.alpha'], query: 'settlement windows', topK: 5 });
  const hit = hits.hits?.[0] ?? {};
  const fieldsOk = typeof hit.text === 'string' && typeof hit.score === 'number' &&
    hit.datasetName === 'qa.alpha';
  record('s2', 'scoped chunk search returns declared fields', fieldsOk ? 'PASS' : 'FAIL',
    { total: hits.total, hitFields: Object.keys(hit), firstScore: hit.score,
      truncated: hits.truncated }, Date.now() - t2);
});

await scenario('s3', 'interface rejections + scoped datasetsStatus', async () => {
  await expectError(
    () => client.request('add', { datasetName: 'evil.other', content: 'x',
      idempotencyKey: 'k-x1' }, { mutating: true }),
    'COGNEE_SCOPE_REJECTED', { id: 's3', name: 'cross-namespace add rejected' });
  await expectError(
    () => client.request('add', { content: 'x', idempotencyKey: 'k-x2' },
      { mutating: true }),
    'COGNEE_SCOPE_REJECTED', { id: 's3', name: 'unscoped add rejected' });
  await expectError(
    () => client.request('search_chunks',
      { datasets: ['qa.alpha', 'evil.secrets'], query: 'x' }),
    'COGNEE_SCOPE_REJECTED', { id: 's3', name: 'cross-namespace search rejected' });
  await expectError(
    () => client.request('add', { datasetName: 'qa.alpha', content: 'x' },
      { mutating: true }),
    'COGNEE_PARAMS_REJECTED',
    { id: 's3', name: 'unkeyed write rejected (VICT blocks unkeyed replay)' });
  const status = await client.request('datasets_status');
  const tStat = Date.now();
  const names = status.datasets.map((d) => d.name);
  const leaks = names.filter((n) => n === 'legacy_unscoped' || n === 'outside.vault');
  const preExistingHidden = status.hiddenDatasets >= 2;
  record('s3', 'datasetsStatus hides pre-existing out-of-domain datasets',
    !leaks.length && preExistingHidden ? 'PASS' : 'FAIL',
    { listed: names, hiddenDatasets: status.hiddenDatasets,
      leaks: leaks.length }, Date.now() - tStat);
  await expectError(
    () => client.request('search_chunks',
      { datasets: ['outside.vault'], query: 'C3FOREIGN' }),
    'COGNEE_SCOPE_REJECTED', { id: 's3', name: 'pre-existing out-of-ns search rejected' });
  const alive = await client.request('ping');
  record('s3', 'worker alive after rejections', alive.pong ? 'PASS' : 'FAIL', {});
});

await scenario('s4', 'keyed reconciliation: interruption -> reissue -> replay', async () => {
  // (a) interrupt a large add mid-flight
  const t = Date.now();
  try {
    await client.request('add', { datasetName: 'qa.delayed', content: delayDoc,
      idempotencyKey: 'k-delay-1' }, { mutating: true, deadlineMs: 400 });
    record('s4', 'delayed add finished before deadline', 'FAIL-UNEXPECTED', {},
      Date.now() - t);
    return;
  } catch (e) {
    if (e.code !== 'COGNEE_WRITE_UNKNOWN') throw e;
    record('s4', 'delayed add -> deadline expiry -> outcome unknown',
      'PASS', { idempotencyKey: e.detail?.idempotencyKey }, Date.now() - t);
  }
  const t2 = Date.now();
  const re1 = await client.request('add', { datasetName: 'qa.delayed',
    content: delayDoc, idempotencyKey: 'k-delay-1' },
    { mutating: true, deadlineMs: 180_000 });
  record('s4', 'reissue after interruption (durable journal)',
    re1.reconciled === 'reissued-after-interruption' && re1.itemsAfter === 1
      ? 'PASS' : 'FAIL', re1, Date.now() - t2);
  const t3 = Date.now();
  const re2 = await client.request('add', { datasetName: 'qa.delayed',
    content: delayDoc, idempotencyKey: 'k-delay-1' },
    { mutating: true, deadlineMs: 60_000 });
  record('s4', 'post-reissue same key replays known outcome',
    re2.reconciled === 'replayed-known-outcome' && re2.itemsAfter === 1
      ? 'PASS' : 'FAIL', re2, Date.now() - t3);
  // (b) interrupt a real cognify, then converge via keyed reissue
  const t4 = Date.now();
  let cognifyInterrupted = false;
  try {
    await client.request('cognify', { datasetName: 'qa.delayed',
      idempotencyKey: 'k-delay-c1' }, { mutating: true, deadlineMs: 4_000 });
    record('s4', 'cognify finished inside 4s window (no interruption to test)',
      'FAIL-UNEXPECTED', {}, Date.now() - t4);
  } catch (e) {
    if (e.code !== 'COGNEE_WRITE_UNKNOWN') throw e;
    cognifyInterrupted = true;
    record('s4', 'cognify interrupted -> outcome unknown', 'PASS',
      { idempotencyKey: 'k-delay-c1' }, Date.now() - t4);
  }
  const t5 = Date.now();
  const con = await client.request('cognify', { datasetName: 'qa.delayed',
    idempotencyKey: 'k-delay-c1' }, { mutating: true, deadlineMs: 240_000 });
  const search = await client.request('search_chunks',
    { datasets: ['qa.delayed'], query: 'C3DELAY', topK: 3 });
  record('s4', 'cognify reissue converges (graph searchable after interruption)',
    (!cognifyInterrupted || con.reconciled === 'reissued-after-interruption') &&
      search.total > 0 ? 'PASS' : 'FAIL',
    { reconciled: con.reconciled, itemsAfter: con.itemsAfter,
      searchTotal: search.total }, Date.now() - t5);
});

await scenario('s5', 'cognify on nonexistent (scoped) dataset', async () => {
  await expectError(
    () => client.request('cognify', { datasetName: 'qa.does_not_exist',
      idempotencyKey: 'k-x3' }, { mutating: true }),
    'COGNEE_DATASET_UNKNOWN', { id: 's5', name: 'cognify nonexistent -> typed failure' });
});

await scenario('s6', 'restart persistence + summary isolation (both sides)', async () => {
  const t = Date.now();
  await client.request('add', { datasetName: 'zeta.bravo', content: zetaDoc,
    idempotencyKey: 'k-zeta-1' }, { mutating: true, deadlineMs: 120_000 });
  await client.request('cognify', { datasetName: 'zeta.bravo',
    idempotencyKey: 'k-zeta-c1' }, { mutating: true, deadlineMs: 240_000 });
  record('s6', 'second-namespace dataset cognified', 'PASS', {}, Date.now() - t);

  const t2 = Date.now();
  const qaHits = await client.request('search_chunks',
    { datasets: ['qa.alpha'], query: 'settlement windows', topK: 5 });
  record('s6', 'restart persistence: qa.alpha still searchable',
    qaHits.total > 0 ? 'PASS' : 'FAIL', { total: qaHits.total }, Date.now() - t2);

  const t3 = Date.now();
  const qaSum = await client.request('search_summaries',
    { datasets: ['qa.alpha'], query: 'settlement windows dual approval', topK: 5 });
  const zetaSum = await client.request('search_summaries',
    { datasets: ['zeta.bravo'], query: 'order router rebalances inventory', topK: 5 });
  const qaLeak = JSON.stringify(qaSum).includes('C3ZETA');
  const zetaLeak = JSON.stringify(zetaSum).includes('C3QA');
  const bothPopulated = qaSum.total > 0 && zetaSum.total > 0;
  record('s6', 'scoped summaries: BOTH sides populated + isolation',
    bothPopulated && !qaLeak && !zetaLeak ? 'PASS' : 'FAIL',
    { qa_total: qaSum.total, zeta_total: zetaSum.total, qaLeak, zetaLeak,
      qaFields: qaSum.hits?.[0] ? Object.keys(qaSum.hits[0]) : [],
      zetaFields: zetaSum.hits?.[0] ? Object.keys(zetaSum.hits[0]) : [] },
    Date.now() - t3);
});

await scenario('s7', 'bounded responses', async () => {
  await expectError(
    () => client.request('search_chunks', { datasets: ['qa.alpha'], query: 'x', topK: 1000 }),
    'COGNEE_PARAMS_REJECTED', { id: 's7', name: 'topK above cap rejected' });
  await expectError(
    () => client.request('search_chunks', { datasets: [], query: 'x' }),
    'COGNEE_PARAMS_REJECTED', { id: 's7', name: 'empty datasets list rejected' });
  const bigLine = 'x'.repeat(1024 * 1024 + 1);
  let lineGuard = 'FAIL-NO-ERROR';
  try {
    await client.request('add', { datasetName: 'qa.alpha', content: bigLine,
      idempotencyKey: 'k-x4' }, { mutating: true, deadlineMs: 5_000 });
  } catch (e) {
    lineGuard = ['LINE_TOO_LARGE', 'CLIENT_DEADLINE', 'COGNEE_WRITE_UNKNOWN',
      'COGNEE_PARAMS_REJECTED'].includes(e.code) ? 'PASS' : `FAIL-WRONG-CODE(${e.code})`;
  }
  record('s7', 'oversized request line refused', lineGuard, {});
});

await scenario('s8', 'forgetDataset (irreversible, no journal, no retry)', async () => {
  const t = Date.now();
  const forgetR = await client.request('forget_dataset', { datasetName: 'qa.delayed' },
    { mutating: true, deadlineMs: 120_000 });
  record('s8', 'forgetDataset receipt', 'PASS',
    { purged: forgetR.purged, filesBefore: forgetR.storeFilesBefore,
      filesAfter: forgetR.storeFilesAfter }, Date.now() - t);
  await expectError(
    () => client.request('search_chunks', { datasets: ['qa.delayed'], query: 'C3DELAY' }),
    'COGNEE_DATASET_UNKNOWN', { id: 's8', name: 'post-forget scoped search typed failure' });
});

await scenario('s9', 'clean shutdown', async () => {
  const t = Date.now();
  await client.shutdown();
  record('s9', 'clean shutdown', 'PASS',
    { stderrLines: client.stderrLines, respawns: client.respawns }, Date.now() - t);
});

const out = {
  proof: 'c3-worker-contract',
  store: 'fresh (proof/.cognee-c3)',
  started: new Date(t0).toISOString(),
  duration_s: Math.round((Date.now() - t0) / 1000),
  results,
};
writeFileSync(path.join(here, 'c3-results.json'), JSON.stringify(out, null, 2));
console.error(`[proof] COMPLETE ${out.duration_s}s — ` +
  `${results.filter((r) => r.outcome === 'PASS').length}/${results.length} PASS`);
process.exit(0); // no lingering worker timers keep the loop alive