/**
 * C4 proof driver — corrected worker boundary vs corrected pack contract.
 *
 * Tests the C4 corrections on top of the C3 contract (fresh disposable store
 * proof/.cognee-c4, own .env + journal, guard boundary = that store):
 *  - retry key EXCLUSIVITY: mutating ops take the key ONLY from the request
 *    `ctx` (VICT CapabilityContext.idempotencyKey); a key in op params is
 *    rejected; a mutation without any ctx key is rejected;
 *  - journal keys are BOUND to (op, dataset, input fingerprint); mismatched
 *    reuse is rejected with COGNEE_IDEMPOTENCY_MISMATCH, journal unchanged;
 *  - FORCED CRASH AFTER Cognee's write but BEFORE the journal commit
 *    (PROOF-ONLY harness worker/worker_proof.py, env C4_PROOF_FAULT — the
 *    pack-bundled worker itself ships NO fault injection): the client reports
 *    COGNEE_WRITE_UNKNOWN (any worker exit during a pending mutation), the
 *    keyed reissue re-executes convergently — item-level convergence for add
 *    (count stays 1, no duplicate) and graph-level convergence for cognify
 *    (dataset searchable after reissue);
 *  - regressions: scope rails, scoped datasetsStatus (seeded foreign
 *    datasets), bounds, summary isolation both sides, forget receipt.
 * Results: worker/c4-results.json; diagnostics: worker/c4.log (stderr).
 */

import { WorkerClient, WorkerError } from './client.mjs';
import { writeFileSync, mkdirSync, rmSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..');
const FRESH = path.join(repo, 'proof', '.cognee-c4');
const PY = path.join(repo, 'proof', '.venv', 'Scripts', 'python.exe');
const NAMESPACES = ['qa', 'zeta'];

// ---- fresh disposable store -------------------------------------------------
for (let attempt = 0; ; attempt++) {
  try {
    rmSync(FRESH, { recursive: true, force: true });
    break;
  } catch (e) {
    if (attempt >= 4) throw e;
    await new Promise((r) => setTimeout(r, 2_000)); // transient EBUSY (Windows)
  }
}
mkdirSync(path.join(FRESH, 'system'), { recursive: true });
const freshRoots = ['system', 'data', 'cache', 'logs', 'repos'];
const envFile = [
  '# Fresh disposable C4 store (generated by worker/proof_c4.mjs — safe to delete)',
  'ENV=dev',
  'RUNTIME__LOG_LEVEL=INFO',
  ...freshRoots.map((r) => {
    const key = { system: 'SYSTEM_ROOT_DIRECTORY', data: 'DATA_ROOT_DIRECTORY',
      cache: 'CACHE_ROOT_DIRECTORY', logs: 'LOGS_ROOT_DIRECTORY',
      repos: 'COGNEE_REPOS_DIR' }[r];
    return `${key}=${path.join(FRESH, r).replace(/\\/g, '/')}`;
  }),
  'VECTOR_DB_PROVIDER=lancedb',
  'GRAPH_DATABASE_PROVIDER=ladybug',
  'DB_PROVIDER=sqlite',
  'EMBEDDING_PROVIDER=fastembed',
  'EMBEDDING_MODEL=BAAI/bge-small-en-v1.5',
  'EMBEDDING_DIMENSIONS=384',
  'GRAPH_EXTRACTOR=gliner_demo',
  'AUTO_FEEDBACK=false',
  '',
].join('\n');
writeFileSync(path.join(FRESH, '.env'), envFile);

// ---- seed pre-existing datasets OUTSIDE the permitted domain ----------------
{
  const t = Date.now();
  const seed = spawnSync(PY, [path.join(repo, 'proof', 'c3_seed_foreign.py')],
    { cwd: FRESH, encoding: 'utf8', timeout: 300_000 });
  const ok = seed.status === 0;
  console.error(`[proof] seed ${ok ? 'ok' : 'FAILED'} (${Date.now() - t}ms)`);
  if (!ok) {
    console.error(String(seed.stderr || '').slice(-2000));
    writeFileSync(path.join(here, 'c4-results.json'), JSON.stringify({
      proof: 'c4-worker-corrections', error: 'seed failed',
      started: new Date().toISOString(), results: [],
    }, null, 2));
    process.exit(1);
  }
}

const results = [];
const t0 = Date.now();

function record(id, name, outcome, detail, ms) {
  results.push({ id, name, outcome, detail, ms });
  console.error(`[proof] ${id} ${outcome} ${name} ${ms ? `(${ms}ms)` : ''}`);
}

function expectError(fn, code, label) {
  const t = Date.now();
  return fn().then(
    () => record(label.id, label.name, 'FAIL-EXPECTED-ERROR', { got: 'success' }, Date.now() - t),
    (e) => record(label.id, label.name,
      e.code === code ? 'PASS' : `FAIL-WRONG-CODE(${e.code})`,
      { expected: code, got: `${e.code}: ${String(e.message).slice(0, 140)}` },
      Date.now() - t));
}

function journalRecords() {
  try {
    return readFileSync(path.join(FRESH, 'system', 'cognee_idempotency_journal.jsonl'),
      'utf8').split('\n').filter((l) => l.trim()).map((l) => JSON.parse(l));
  } catch {
    return [];
  }
}

const client = new WorkerClient(PY, path.join(repo, 'pack', 'src', 'worker', 'cognee_worker.py'),
  { cwd: FRESH, namespaces: NAMESPACES, readyBudgetMs: 180_000,
    storeRoot: FRESH, diag: (m) => console.error(m) });

/** Crash-window client: same store, but with the PROOF-ONLY fault hook armed. */
function crashClient(fault) {
  // PROOF-ONLY crash harness: the pack-bundled worker ships with NO fault
  // injection; worker_proof.py patches the journal commit under C4_PROOF_FAULT.
  return new WorkerClient(PY, path.join(repo, 'worker', 'worker_proof.py'),
    { cwd: FRESH, namespaces: NAMESPACES, readyBudgetMs: 180_000,
      storeRoot: FRESH, env: { C4_PROOF_FAULT: fault }, diag: (m) => console.error(m) });
}

const OBS_CODES = ['COGNEE_WORKER_UNAVAILABLE', 'COGNEE_WRITE_UNKNOWN', 'CLIENT_DEADLINE'];

async function scenario(id, name, fn) {
  const t = Date.now();
  try {
    await fn();
  } catch (e) {
    record(id, name, OBS_CODES.includes(e.code) ? 'AGENT-OBSERVATION' : 'ERROR',
      { code: e.code ?? '?', message: String(e.message ?? e).slice(0, 220) },
      Date.now() - t);
    try { await client._lifecycle(); } catch { /* respawn best-effort */ }
  }
}

const qaDoc = 'Quellight C3QA marker: settlement windows close at 17:00 local time; ' +
  'ledger reconciliation runs nightly under dual approval; exceptions escalate ' +
  'to the on-call settlement controller before the next business day.';
const zetaDoc = 'Trading OS C3ZETA marker: the order router rebalances inventory ' +
  'positions at the 09:30 open; fills above the notional band require a second ' +
  'approver before the rebalance is published to the trading journal.';
const crashDoc = 'C4CRASH marker: the crash-window add lands in cognee before the ' +
  'journal commit is forced to exit; the keyed reissue must converge without ' +
  'duplicating the item.';

await scenario('c1', 'startup guard + ready (fresh store, protocol v4)', async () => {
  const t = Date.now();
  const ready = await client.ensureReady();
  const correctStore = String(ready.store_root).startsWith(FRESH);
  record('c1', 'startup guard + ready (fresh store)',
    ready.allowed_namespaces && correctStore &&
      String(ready.protocol).startsWith('vict-cognee-worker/') ? 'PASS' : 'FAIL',
    { protocol: ready.protocol, import_ms: ready.import_ms,
      namespaces: ready.allowed_namespaces, storeRoot: ready.store_root,
      rss_mb: Math.round(ready.rss_bytes / 1e6) }, Date.now() - t);
});

await scenario('c2', 'retry key exclusivity (ctx-only)', async () => {
  await expectError(
    () => client.request('add', { datasetName: 'qa.alpha', content: qaDoc,
      idempotencyKey: 'k-smuggled' }, { mutating: true, ctx: { idempotencyKey: 'k-real' } }),
    'COGNEE_PARAMS_REJECTED',
    { id: 'c2', name: 'key in op params rejected (ctx exclusivity)' });
  await expectError(
    () => client.request('add', { datasetName: 'qa.alpha', content: qaDoc },
      { mutating: true }),
    'COGNEE_PARAMS_REJECTED',
    { id: 'c2', name: 'mutating op without ctx key rejected' });
  await expectError(
    () => client.request('cognify', { datasetName: 'qa.alpha' }, { mutating: true }),
    'COGNEE_PARAMS_REJECTED',
    { id: 'c2', name: 'cognify without ctx key refused (no silent no-op path)' });
});

await scenario('c3', 'fresh-execution + replay + search (qa.alpha)', async () => {
  const t = Date.now();
  const add1 = await client.request('add', { datasetName: 'qa.alpha', content: qaDoc },
    { mutating: true, deadlineMs: 120_000, ctx: { idempotencyKey: 'k2-1' } });
  record('c3', 'add fresh-execution with item counts',
    add1.reconciled === 'fresh-execution' && add1.itemsAfter === 1 ? 'PASS' : 'FAIL',
    add1, Date.now() - t);
  const t2 = Date.now();
  const add2 = await client.request('add', { datasetName: 'qa.alpha', content: qaDoc },
    { mutating: true, deadlineMs: 60_000, ctx: { idempotencyKey: 'k2-1' } });
  record('c3', 'same key replays known outcome (no re-exec)',
    add2.reconciled === 'replayed-known-outcome' && add2.itemsAfter === 1
      ? 'PASS' : 'FAIL', add2, Date.now() - t2);
  const t3 = Date.now();
  await client.request('cognify', { datasetName: 'qa.alpha' },
    { mutating: true, deadlineMs: 240_000, ctx: { idempotencyKey: 'k2-cog' } });
  const hits = await client.request('search_chunks',
    { datasets: ['qa.alpha'], query: 'settlement windows', topK: 5 });
  const hit = hits.hits?.[0] ?? {};
  const fieldsOk = typeof hit.text === 'string' && typeof hit.score === 'number' &&
    hit.datasetName === 'qa.alpha';
  record('c3', 'scoped chunk search returns declared fields', fieldsOk ? 'PASS' : 'FAIL',
    { total: hits.total, hitFields: Object.keys(hit), firstScore: hit.score,
      truncated: hits.truncated }, Date.now() - t3);
});

await scenario('c4', 'journal binding: key -> (op, dataset, fingerprint)', async () => {
  const t = Date.now();
  await expectError(
    () => client.request('add', { datasetName: 'qa.alpha',
      content: qaDoc + ' DIFFERENT CONTENT' },
      { mutating: true, ctx: { idempotencyKey: 'k2-1' } }),
    'COGNEE_IDEMPOTENCY_MISMATCH',
    { id: 'c4', name: 'same key + different content rejected (fingerprint)' });
  await expectError(
    () => client.request('add', { datasetName: 'qa.other', content: qaDoc },
      { mutating: true, ctx: { idempotencyKey: 'k2-1' } }),
    'COGNEE_IDEMPOTENCY_MISMATCH',
    { id: 'c4', name: 'same key + different dataset rejected' });
  await expectError(
    () => client.request('add', { datasetName: 'qa.alpha', content: qaDoc },
      { mutating: true, ctx: { idempotencyKey: 'k2-cog' } }),
    'COGNEE_IDEMPOTENCY_MISMATCH',
    { id: 'c4', name: 'key bound to cognify rejected for add (op mismatch)' });
  // journal unchanged: k2-1 still resolves to the ORIGINAL outcome afterwards
  const replay = await client.request('add', { datasetName: 'qa.alpha', content: qaDoc },
    { mutating: true, ctx: { idempotencyKey: 'k2-1' } });
  record('c4', 'mismatches left journal state intact (replay unchanged)',
    replay.reconciled === 'replayed-known-outcome' && replay.itemsAfter === 1
      ? 'PASS' : 'FAIL', replay, Date.now() - t);
});

await scenario('c5', 'forced crash AFTER add write, BEFORE journal commit', async () => {
  // ONE worker per store: park the main worker before arming the crash worker.
  await client.shutdown();
  const cc = crashClient('add.after-write-before-commit');
  const t = Date.now();
  try {
    await cc.ensureReady();
    await cc.request('add', { datasetName: 'qa.crashadd', content: crashDoc },
      { mutating: true, deadlineMs: 180_000, ctx: { idempotencyKey: 'k5' } });
    record('c5', 'crash hook did not fire (add completed)', 'FAIL-UNEXPECTED', {},
      Date.now() - t);
    return;
  } catch (e) {
    if (e.code !== 'COGNEE_WRITE_UNKNOWN') throw e;
    record('c5', 'worker exit during pending add -> COGNEE_WRITE_UNKNOWN',
      e.detail?.workerExit?.code === 2 ? 'PASS' : 'FAIL',
      { idempotencyKey: 'k5', workerExit: e.detail?.workerExit }, Date.now() - t);
  }
  // journal now holds exactly the crash evidence: begun WITHOUT completed
  const afterCrash = journalRecords().filter((r) => r.key === 'k5');
  record('c5', 'journal shows begun-without-commit after the forced crash',
    afterCrash.length === 1 && afterCrash[0].state === 'begun' ? 'PASS' : 'FAIL',
    { records: afterCrash.map((r) => r.state) });
  const t2 = Date.now();
  const re1 = await client.request('add', { datasetName: 'qa.crashadd',
    content: crashDoc }, { mutating: true, deadlineMs: 180_000,
    ctx: { idempotencyKey: 'k5' } });
  record('c5', 'reissue after crash-before-commit re-executes convergently',
    re1.reconciled === 'reissued-after-interruption' && re1.itemsAfter === 1
      ? 'PASS' : 'FAIL', // item-level convergence: landed write + re-exec = 1 item
    re1, Date.now() - t2);
  const t3 = Date.now();
  const re2 = await client.request('add', { datasetName: 'qa.crashadd',
    content: crashDoc }, { mutating: true, ctx: { idempotencyKey: 'k5' } });
  record('c5', 'post-reissue same key replays known outcome',
    re2.reconciled === 'replayed-known-outcome' && re2.itemsAfter === 1
      ? 'PASS' : 'FAIL', re2, Date.now() - t3);
});

await scenario('c6', 'forced crash AFTER cognify write, BEFORE commit', async () => {
  const t = Date.now();
  await client.request('add', { datasetName: 'qa.cognicrash', content: crashDoc },
    { mutating: true, deadlineMs: 120_000, ctx: { idempotencyKey: 'k6a' } });
  // ONE worker per store: park the main worker before arming the crash worker.
  // A cognee-internal cognify failure (flaky class) leaves begun-without-commit
  // in the journal — the retry below re-arms the hook and re-executes the SAME
  // key, which the journal reconciles exactly like a real interruption.
  for (let attempt = 1; attempt <= 2; attempt++) {
    await client.shutdown();
    const cc = crashClient('cognify.after-write-before-commit');
    try {
      await cc.ensureReady();
      await cc.request('cognify', { datasetName: 'qa.cognicrash' },
        { mutating: true, deadlineMs: 240_000, ctx: { idempotencyKey: 'k6' } });
      record('c6', `cognify crash hook did not fire (attempt ${attempt})`,
        'FAIL-UNEXPECTED', {}, Date.now() - t);
      return;
    } catch (e) {
      if (e.code === 'COGNEE_WRITE_UNKNOWN' &&
          e.detail?.workerExit?.code === 2) {
        record('c6', 'worker exit during pending cognify -> COGNEE_WRITE_UNKNOWN',
          'PASS', { idempotencyKey: 'k6', workerExit: e.detail?.workerExit,
            attempt }, Date.now() - t);
        break;
      }
      if (attempt === 2 || e.code !== 'COGNEE_ERROR') throw e;
      record('c6', `cognify failed internally before the hook (attempt ${attempt}); retrying`,
        'AGENT-OBSERVATION', { code: e.code,
          message: String(e.message).slice(0, 120) });
    }
  }
  const afterCrash = journalRecords().filter((r) => r.key === 'k6');
  record('c6', 'journal shows begun-without-commit after the forced cognify crash',
    afterCrash.length >= 1 &&
      afterCrash[afterCrash.length - 1].state === 'begun' ? 'PASS' : 'FAIL',
    { records: afterCrash.map((r) => r.state) });
  const t2 = Date.now();
  const con = await client.request('cognify', { datasetName: 'qa.cognicrash' },
    { mutating: true, deadlineMs: 240_000, ctx: { idempotencyKey: 'k6' } });
  const search = await client.request('search_chunks',
    { datasets: ['qa.cognicrash'], query: 'C4CRASH', topK: 3 });
  record('c6', 'cognify reissue converges (graph searchable after interruption)',
    con.reconciled === 'reissued-after-interruption' && search.total > 0
      ? 'PASS' : 'FAIL',
    { reconciled: con.reconciled, itemsAfter: con.itemsAfter,
      searchTotal: search.total }, Date.now() - t2);
});

await scenario('c7', 'regressions: scope rails + scoped datasetsStatus', async () => {
  await expectError(
    () => client.request('add', { datasetName: 'evil.other', content: 'x' },
      { mutating: true, ctx: { idempotencyKey: 'k-x1' } }),
    'COGNEE_SCOPE_REJECTED', { id: 'c7', name: 'cross-namespace add rejected' });
  await expectError(
    () => client.request('add', { content: 'x' }, { mutating: true, ctx: { idempotencyKey: 'k-x2' } }),
    'COGNEE_SCOPE_REJECTED', { id: 'c7', name: 'unscoped add rejected' });
  await expectError(
    () => client.request('search_chunks',
      { datasets: ['qa.alpha', 'evil.secrets'], query: 'x' }),
    'COGNEE_SCOPE_REJECTED', { id: 'c7', name: 'cross-namespace search rejected' });
  const status = await client.request('datasets_status');
  const names = status.datasets.map((d) => d.name);
  const leaks = names.filter((n) => n === 'legacy_unscoped' || n === 'outside.vault');
  record('c7', 'datasetsStatus hides pre-existing out-of-domain datasets',
    !leaks.length && status.hiddenDatasets >= 2 ? 'PASS' : 'FAIL',
    { listed: names, hiddenDatasets: status.hiddenDatasets });
  await expectError(
    () => client.request('search_chunks',
      { datasets: ['outside.vault'], query: 'C3FOREIGN' }),
    'COGNEE_SCOPE_REJECTED', { id: 'c7', name: 'pre-existing out-of-ns search rejected' });
  await expectError(
    () => client.request('search_chunks', { datasets: ['qa.alpha'], query: 'x', topK: 1000 }),
    'COGNEE_PARAMS_REJECTED', { id: 'c7', name: 'topK above cap rejected' });
  const bigLine = 'x'.repeat(1024 * 1024 + 1);
  let lineGuard = 'FAIL-NO-ERROR';
  try {
    await client.request('add', { datasetName: 'qa.alpha', content: bigLine },
      { mutating: true, deadlineMs: 5_000, ctx: { idempotencyKey: 'k-x4' } });
  } catch (e) {
    lineGuard = ['LINE_TOO_LARGE', 'CLIENT_DEADLINE', 'COGNEE_WRITE_UNKNOWN',
      'COGNEE_PARAMS_REJECTED'].includes(e.code) ? 'PASS' : `FAIL-WRONG-CODE(${e.code})`;
  }
  record('c7', 'oversized request line refused', lineGuard, {});
});

await scenario('c8', 'restart persistence + summary isolation (both sides)', async () => {
  const t = Date.now();
  await client.request('add', { datasetName: 'zeta.bravo', content: zetaDoc },
    { mutating: true, deadlineMs: 120_000, ctx: { idempotencyKey: 'k-zeta-1' } });
  await client.request('cognify', { datasetName: 'zeta.bravo' },
    { mutating: true, deadlineMs: 240_000, ctx: { idempotencyKey: 'k-zeta-c1' } });
  record('c8', 'second-namespace dataset cognified', 'PASS', {}, Date.now() - t);
  const t2 = Date.now();
  const qaSum = await client.request('search_summaries',
    { datasets: ['qa.alpha'], query: 'settlement windows dual approval', topK: 5 });
  const zetaSum = await client.request('search_summaries',
    { datasets: ['zeta.bravo'], query: 'order router rebalances inventory', topK: 5 });
  const qaLeak = JSON.stringify(qaSum).includes('C3ZETA');
  const zetaLeak = JSON.stringify(zetaSum).includes('C3QA');
  const bothPopulated = qaSum.total > 0 && zetaSum.total > 0;
  record('c8', 'scoped summaries: BOTH sides populated + isolation',
    bothPopulated && !qaLeak && !zetaLeak ? 'PASS' : 'FAIL',
    { qa_total: qaSum.total, zeta_total: zetaSum.total, qaLeak, zetaLeak },
    Date.now() - t2);
  const t3 = Date.now();
  const qaHits = await client.request('search_chunks',
    { datasets: ['qa.alpha'], query: 'settlement windows', topK: 5 });
  record('c8', 'restart persistence: qa.alpha still searchable',
    qaHits.total > 0 ? 'PASS' : 'FAIL', { total: qaHits.total }, Date.now() - t3);
});

await scenario('c9', 'forgetDataset (irreversible, no journal, no retry)', async () => {
  const t = Date.now();
  const forgetR = await client.request('forget_dataset', { datasetName: 'qa.crashadd' },
    { mutating: true, deadlineMs: 120_000 });
  record('c9', 'forgetDataset receipt', 'PASS',
    { purged: forgetR.purged, filesBefore: forgetR.storeFilesBefore,
      filesAfter: forgetR.storeFilesAfter }, Date.now() - t);
  await expectError(
    () => client.request('search_summaries', { datasets: ['qa.crashadd'], query: 'crash' }),
    'COGNEE_DATASET_UNKNOWN',
    { id: 'c9', name: 'post-forget scoped search typed failure' });
  // forget is never journaled: no journal record carries the forget op
  const forgetJournaled = journalRecords().some((r) => r.op === 'forget_dataset');
  record('c9', 'forgetDataset left no journal record', !forgetJournaled ? 'PASS' : 'FAIL',
    { forgetJournaled });
});

await scenario('c10', 'clean shutdown', async () => {
  const t = Date.now();
  await client.shutdown();
  record('c10', 'clean shutdown', 'PASS',
    { stderrLines: client.stderrLines, respawns: client.respawns }, Date.now() - t);
});

const out = {
  proof: 'c4-worker-corrections',
  store: 'fresh (proof/.cognee-c4)',
  started: new Date(t0).toISOString(),
  duration_s: Math.round((Date.now() - t0) / 1000),
  results,
};
writeFileSync(path.join(here, 'c4-results.json'), JSON.stringify(out, null, 2));
console.error(`[proof] COMPLETE ${out.duration_s}s — ` +
  `${results.filter((r) => r.outcome === 'PASS').length}/${results.length} PASS`);
process.exit(0); // no lingering worker timers keep the loop alive